### ISSUE TITLE
Common questions about MAPI

### ISSUE THREAD

**Issue by DevMichaelSabo** [stephenegriffin/mfcmapi#102]
Hello Stephen,

because I never found a valid email address of you, I open a pseudo ticket/issue. Not nice, I know. But if you have a mail address for me, we can talk in future directly.

I work now a longer time with MAPI and several things become more and more clearly about time. But some things are not totally clearly for me and it is painful/hard to google those information.

-- First thing: ONLINE / OFFLINE Mode
I thought until now, the online mode is only a cached view. But I see, the structure has more differences as I thought. In online mode I have a property `PR_CONTAINER_CONTENTS`, `PR_CONTAINER_HIERARCHY`
 and `PR_FOLDER_ASSOCIATED_CONTENTS`. In offline mode, not. Why? Is there a reason?
Are this 2 different providers? Is this the reason, why `GetProps `works with parameter `null `(to get all properties in online mode) works and in offline mode not? A first explicit call to `GetPropList()` is necessary, how I saw it in your code.
If I like to download all items, must I be necessary in ONLINE Mode? I thought missing items (i mean not yet in cache) would be in background automatically transfered/pulled. Next time, I get the cached item. But I see, I get only a minimal subset of all items in a new .ost (automatically created by MAPI via OpenMsgStore)

-- Second thing: Can I detect the configured offline/offline mode? (how user configered his connection to mailbox in outlook? non-cached, chached, if yes, the timeout)
Indirectly I can check the existance of properties above. But is this a good practise?
Outlook can show: there are more items, please click to load. Do you know how Outlook implements this feature. 2 MAPI Sessions, one offline, one online and compares the row count?

-- Third thing: Object types / `PR_OBJECT_TYPE` and named properties
It is possible to use this value for determinate the object and interface  (e.g. `IMAPIFolder`, `IMessage`), ok. Every of them are derived from `IMAPIProp`. `IMAPIProp` contains `GetNamesFromIDs()`. So every object could implement a different named property storage. Is this right? Or does every object use and access a global named property table? I see, you implement a cache in MFCMAPI, too.

Have a happy christmas, thanks.

Regards,
Michael

**Comment by stephenegriffin** [comment]
Online is a mailbox on the Exchange server. Cached mode is an OST. We use ICS to synchronize folders between the two, but not everything is sync'd. They're two separate stores, so there will be differences.

This issues list is for problem with MFCMAPI. Please do not abuse it.

**Comment by DevMichaelSabo** [comment]
Ok, where is a better place to contact you for a professional help?

Oh really, that's all!? *lol*
It only controls wheather you want to access the mailbox on the server or on the local .pst file.
I am surprised, because I thought in offline mode is the syncronisation build in there (in MAPI itself). But if I understand you right, the synchronisation is implemented by outlook.

But then I ask myself, why is the reading out of elements in a .pst is very very fast and a .ost very slow. The speed of the online and offline mode does not really differ. I have explained this slow speed for me, that the accessed element has to be checked for up-to-date and a slow connection (RTT) with the office 365 server must be established and, if necessary, to download it again. But if I understand you right, the synchronisation is done by outlook itself and not by MAPI.

By the way:
What kind of role does PR_FOLDER_ASSOCIATED_CONTENTS play? This only exists in a .ost, right?
The container holds only settings of outlook and control information of exchange (e.g. data/properties of Messaging Records Management (MRM)). That's right?
