### ISSUE TITLE
Error converting EML to MSG - MFCMAPI, office 2016 - current branch

### ISSUE THREAD

**Issue by kansasdev** [stephenegriffin/mfcmapi#103]
I would like to suggest issue which I have been working with for few days.
To reproduce an error you are doing following steps:
1. Install newest Office 2016 and upgrade it to current branch using Outlook itself - File, Office account field and then upgrading directly from Office (1711 version at the moment)
2. Prepare registry to expose imimeconverter, in my case:
`
[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Classes\CLSID\{9EADBD10-447B-4240-A9DD-73FE7C53A981}]
@="CLSID_IMimeInternational"

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Classes\CLSID\{9EADBD10-447B-4240-A9DD-73FE7C53A981}\InprocServer32]
@="C:\\Program Files (x86)\\Microsoft Office\\Root\\Office16\\OUTLMIME.DLL"
"ThreadingModel"="Both"

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Classes\CLSID\{9EADBD10-447B-4240-A9DD-73FE7C53A981}\Typelib]
@="{9EADBD25-447B-4240-A9DD-73FE7C53A981}"`

3. Prepare registry to expose iconvertersession, in my case:
`[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Classes\CLSID\{4E3A7680-B77A-11D0-9DA5-00C04FD65685}]
@="CLSID_IConverterSession"

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Classes\CLSID\{4E3A7680-B77A-11D0-9DA5-00C04FD65685}\InprocServer32]
@="C:\\Program Files (x86)\\Microsoft Office\\Root\\Office16\\OUTLMIME.DLL"
"ThreadingModel"="Both"`

4. Run mfcmapi (x86 version in my case) and then proces to "Advanced", "Import/Export" and finally "Convert EML to MSG", giving some eml file I am getting below warning:
`**Warning: 
Code: MAPI_W_PARTIAL_COMPLETION == 0x00040680
Function lpConverter->MIMEToMAPI(lpEMLStm, lpMsg, nullptr, ulConvertFlags)
File MapiMime.cpp
Line 53
**`
File is being produced but file is **unreadable** by Outlook
Workaround is to uninstall Outlook totally using [https://support.office.com/en-us/article/Uninstall-Office-from-a-PC-9dd49b83-264a-477a-8fcc-2fdf5dbf61d8](url)
and install Outlook 2016 from discontinued line - I have found such version from my msdn account - it was 16.0.4266.1003 and then set Outlook to **stop** receiving updates - if you receive any update from internet, l have found it will cause converting functionality to stop working. I have been trying also to reverse back to some older versions using OfficeClickToRun.exe like 1611, 1703 but without success.
Do you have any workarounds for such problem?

**Comment by warrenlbrown** [comment]
MS apparently broke this in Outlook 2016 around June of last year (2017). If I revert to right before that version, I have no problems. If I use Outlook 2013, I have no problems. This is actually a very critical problem. Any chance that somebody will look into whatever broke in the MAPItoMime stuff.  Thank you.

**Comment by warrenlbrown** [comment]
As you know, it is virtually impossible to get through to the right level of support within Microsoft for this kind of problem. So any chance you, Stephen, can facilitate this, at least by getting the proper support person/group involved sooner rather than later. Many thanks.

**Comment by warrenlbrown** [comment]
Many thanks. We reverted the two reg hacks needed for other issues over the past few years. viz:
`rem IConverterSession
REG COPY HKLM\SOFTWARE\Microsoft\Office\ClickToRun\REGISTRY\MACHINE\Software\Classes\Wow6432Node\CLSID\{4E3A7680-B77A-11D0-9DA5-00C04FD65685} HKLM\SOFTWARE\Classes\Wow6432Node\CLSID\{4E3A7680-B77A-11D0-9DA5-00C04FD65685} /s /f
rem IMimeMessage
REG COPY HKLM\SOFTWARE\Microsoft\Office\ClickToRun\REGISTRY\MACHINE\Software\Classes\Wow6432Node\CLSID\{9EADBD1A-447B-4240-A9DD-73FE7C53A981} HKLM\SOFTWARE\Classes\Wow6432Node\CLSID\{9EADBD1A-447B-4240-A9DD-73FE7C53A981} /s /f`

Now when I run your latest mfcmapi code 32-bit, Advanced, Import Convert EML to MSG I get a series of error dialogs such as 
[mfcmapieml.zip](https://github.com/stephenegriffin/mfcmapi/files/2006374/mfcmapieml.zip)

**Comment by stephenegriffin** [comment]
Right - those errors would then be expected, as the com objects that host those API are not registered/exposed, which is by design for 2016 C2R. If anything, I need to patch MFCMAPI to better understand this scenario and display a more proper error.

**Comment by warrenlbrown** [comment]
OK, but that still does not fix the underlying problem with MimeToMapi dll conversion which appears to have been broken in OL2016 around June 2017. Does the EML->MSG conversion work for you with MFCMAPI using stock OL2016 C2R?

**Comment by warrenlbrown** [comment]
Or are you saying, that we can no longer use this capability if somebody has installed OL2016 C2R (and fugures)? ie, We now have to roll our own?  Thanks again for your quick responses and help.

**Comment by stephenegriffin** [comment]
That is the current design, yes. 2016 C2R does not expose these APIs for consumption.
