### ISSUE TITLE
Another question: PR_LAST_MODIFICATION_TIME

### ISSUE THREAD

**Issue by DevMichaelSabo** [stephenegriffin/mfcmapi#105]
Hi Stephen!
If you read a message in outlook or reset it to unread state, I expect that the property PR_LAST_MODIFICATION_TIME is updated. 

https://msdn.microsoft.com/de-de/library/office/cc815542.aspx

> When SaveChanges is called, the message store provider updates the following properties:
> ...
> PR_LAST_MODIFICATION_TIME (PidTagLastModificationTime)
> ...
> 

https://msdn.microsoft.com/de-de/library/office/cc815689.aspx

> From then on the provider should update PR_LAST_MODIFICATION_TIME during every IMAPIProp::SaveChanges call.

I think, outlook have to call SaveChanges after modifiing PR_MESSAGE_FLAGS. But I observe only a date/time change in PR_LAST_MODIFICATION_TIME if you change body, category and so on.

Is this flag not a reliable indicator to detect changes to mails and other items??

Regards

**Comment by stephenegriffin** [comment]
[PR_MESSAGE_FLAGS](https://msdn.microsoft.com/en-us/library/cc839733(v=office.15).aspx) is a computed property. It can be altered without calling SaveChanges. For instance, you can toggle read/unread status with [SetReadFlag](https://msdn.microsoft.com/en-us/library/office/cc815395.aspx).

If you want to watch for changes to a message, you should be using notifications and/or [Incremental Change Synchonization (ICS)](https://blogs.msdn.microsoft.com/stephen_griffin/2008/01/31/where-did-i-put-those-5-5-sdk-docs/).

**Comment by DevMichaelSabo** [comment]
Thanks a lot for the keyword ICS!

But both technologies are intended for runtime. My intention is to detected changes between two executions of my programm. I however, search a easy and **fast** (very important) way to detect changes on items. I see, unfortunately a simple compare of PR_LAST_MODIFICATION_TIME is not enough.

Which properties should I compare for a secure detection?
- PR_LAST_MODIFICATION_TIME
- PR_MESSAGE_FLAGS
- ?

How would you proceed in this case?
