### ISSUE TITLE
Unable to delete

### ISSUE THREAD

**Issue by tonyc2000** [stephenegriffin/mfcmapi#106]
Stephen;
I am using Win7 64bit; Outlook 2016 32 bit (Version 1711 Build 8730.2165 Click to Run)

I want to restore the AutoComplete cache from a PST file (IMAP) that was backed up before wiping and reinstalling Win7 and Outlook.  I captured/saved the IPM.Configuration.Autocomplete from the old Mailbox.  Next step was to delete IPM.Configuration.Autocomplete from the existing (new) Mailbox:

1. Start MFCMAPIx86 (latest build)
2. Session>Logon
3. Double click the existing configured mailbox
4. Expand IPM_Subtree
5. Right click Inbox; open associated contents table
6. Right click IPM.Configuration.Autocomplete
7. Choose 'Delete Message' Permanent Deletion (to deleted item retention)
8.  MFCMAPI App Crashes

From Event Viewer:
Faulting application name: MFCMAPI.exe, version: 17.0.17099.1, time stamp: 0x58ea5de1
Faulting module name: pstprx32.dll, version: 16.0.8730.2127, time stamp: 0x5a2a29fe
Exception code: 0xc0000005
Fault offset: 0x0003dbfd
Faulting process id: 0x21cc
Faulting application start time: 0x01d388332f64928e
Faulting application path: G:\Users\Tony\Downloads\MFCMAPI\MFCMapi.exe.17.0.17099.01\MFCMAPI.exe
Faulting module path: C:\Program Files (x86)\Microsoft Office\root\Office16\pstprx32.dll
Report Id: a429813c-f426-11e7-9cc2-2c4d54ec988b

From AppCrash details:
Problem Event Name:	APPCRASH
  Application Name:	MFCMAPI.exe
  Application Version:	17.0.17099.1
  Application Timestamp:	58ea5de1
  Fault Module Name:	pstprx32.dll
  Fault Module Version:	16.0.8730.2127
  Fault Module Timestamp:	5a2a29fe
  Exception Code:	c0000005
  Exception Offset:	0003dbfd
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Hope you can help!
Tony .

**Comment by stephenegriffin** [comment]
This, of course, means it's not me. :)
>Faulting module path: C:\Program Files (x86)\Microsoft Office\root\Office16\pstprx32.dll

I'll see if I can match it to something known in Outlook.

**Comment by stephenegriffin** [comment]
For my own records, this is bucket c68977c1-34fe-1d56-b3d2-2bc68a08c713.

I didn't find any open bugs on this. If it does bubble up as a concern it'll be useful to have these repro steps. Thanks!

**Comment by tonyc2000** [comment]
Stephen;

Thank you.  I interpret this to mean there is no solution for the time being.

Thanks for looking at it and responding so quickly !

 

Tony C.

**Comment by kilobajt** [comment]
Same happens to us with newest Outlook 365 on all 6 computers and on both x86 and x64 Outlook editions. We can't import older autocomplete lists and it's really annoying. We are using same steps as tonyc2000. Is there any other way to import autocomplete list? We really need it.

Crash info:
Napačno ime programa: MFCMAPI.exe, različica: 19.2.19058.831, časovni žig: 0x5c75fa9b
Napačno ime modula: pstprx32.dll, različica: 16.0.11231.20120, časovni žig: 0x5c48dc13
Koda izjeme: 0xc0000005
Napačen odmik: 0x00000000001461d0
Napačen id procesa: 0x3954
Napačen začetni čas programa: 0x01d4ce8c80a04caa
Napačna programska pot: C:\Users\Borut\Downloads\MFCMAPI.exe.x64.19.2.19058.831\MFCMAPI.exe
Napačna pot modula: C:\Program Files\Microsoft Office\Root\Office16\pstprx32.dll
Id poročila: 815f6a0b-6f00-4e16-88a7-f459a63fcb4b
Napačno polno ime paketa: 
Napačen ID programa, sorodnega paketu:
