### ISSUE TITLE
Access to PidLidContactLinkEntry or PidLidContactLinkName?

### ISSUE THREAD

**Issue by Sachelis** [stephenegriffin/mfcmapi#107]
Does MFCMAPI provide access to PidLidContactLinkEntry or PidLidContactLinkName? I'm trying to find out how I can determine if a contact is linked to another contact (and ultimately, how to unlink them). I did find [this article](https://blogs.msdn.microsoft.com/emeamsgdev/2014/06/17/programmatically-add-links-to-outlook-contactitems-in-outlook-2013/) which provide some information on linking contacts and mentions these properties.

 FYI, I'm early in this process and haven't downloaded your source code... I'm just running the executable.

Thanks. Sorry for the slightly-off-topic question.

**Comment by stephenegriffin** [comment]
They're just properties - they should be available.
