### ISSUE TITLE
Having Export/Import problem with the AutoComplete Cache

### ISSUE THREAD

**Issue by tnttek** [stephenegriffin/mfcmapi#110]
As soon as I attempt to Import the saved msg file, the application crashes with "MFCMAPI x64 has stopped working"

Do you have any suggestions?

New computer from Dell.  Never has been used.

Winver: 1709 (16299.214)
MFCMapi: x64.17.0.17099.01

**Comment by stephenegriffin** [comment]
likely no longer repros
