### ISSUE TITLE
Outlook MS Home and Business 2016 not detected

### ISSUE THREAD

**Issue by SMSOutthere** [stephenegriffin/mfcmapi#125]
Good Morning, 

I downloaded your utility to delete a stuck message as we have the Send/Receive issue. When I tried to go Session>Logon it told me that Outlook is not installed.

We are using MS Office Home and Business 2016 and I used the 64bit utility.

Your assistance is appreciated.

Thanks

Sean

**Comment by stephenegriffin** [comment]
Try the 32 bit build of mfcmapi

**Comment by stephenegriffin** [comment]
That is, x86
