### ISSUE TITLE
Possible to use MFCMAPI against other user mailbox? Use in bulk/scripted?

### ISSUE THREAD

**Issue by NoahsMyBro** [stephenegriffin/mfcmapi#128]
I need to update a large # of user's Outlooks to alter the displayed mailbox name (the label at the top of the folder tree).

I don't want to recreate all user Outlook profiles.

I've found that I can use MFCMAPI on an individual computer to make the change on the user's Outlook profile.

I'm hoping I can leverage this to use it against the full environment of ~200 users. 

Is it possible to:

- somehow script or otherwise use MFCMAPI to make the change administratively, in-bulk, against all users? I've got a 3rd-party deployment tool at my disposal, as well as AD and Group Policy. I can push out ps or vbs scripts easily enough.

- Use MFCMAPI against O365 mailboxes, log in using an admin account and administer properties of a different mailbox in the tenant?

- when run, have MFCMAPI automatically apply the change I need to the user's default profile in case the user has more than one profile configured?

Thanks.

**Comment by stephenegriffin** [comment]
Nope. No automation in mfcmapi

**Comment by NoahsMyBro** [comment]
Bummer. Thanks for letting me know, at least, and for maintaining this cool tool.
