### ISSUE TITLE
Unable to delete a Named Property

### ISSUE THREAD

**Issue by LastDomino** [stephenegriffin/mfcmapi#129]
We have a poorly written Outlook Add-in, that is generating thousands of Named Properties, and I was hoping I could use the mfcmapi tool to delete some of them  (while I look for a better way).

I select one of these custom Named Properties, right click, and select "Delete Property", but it only opens an error window.

This is the error message that is presented.

Error: 
Code: MAPI_E_NO_SUPPORT == 0x80040102
Function m_lpPropBag->DeleteProp(ulPropTag)
File UI\Controls\SingleMAPIPropListCtrl.cpp
Line 1169

**Comment by stephenegriffin** [comment]
That would be the store/server telling you no there...
