### ISSUE TITLE
MFCMAPI crashes when opening associated items

### ISSUE THREAD

**Issue by EinmalIM** [stephenegriffin/mfcmapi#139]
Open associated items crashes with MFCMAPI 18.2.18154.97 64-bit on Outlook 2016 MAPI 1805 (9330.2087 C2R). Our Exchange is 2016 On-Prem (15.1.1466.8 when looking at OWA html sources).

I logged on to my Outlook profile for my cached mailbox: no matter on which folder I try to open the associated items, MFCMAPI crashes.

Regards
Sven

**Comment by EinmalIM** [comment]
Crash occurs on dynamic_cast<LPMAPIFOLDER> in MsgStoreDlg.cpp

`
	void CMsgStoreDlg::OnDisplayAssociatedContents()
	{
		if (!m_lpHierarchyTableTreeCtrl) return;

		// Find the highlighted item
		auto lpMAPIFolder = dynamic_cast<LPMAPIFOLDER>(m_lpHierarchyTableTreeCtrl->GetSelectedContainer(mfcmapiREQUEST_MODIFY));
`

This is with VS 2017 15.7.3 in rtti.cpp (C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\crt\src\vcruntime\rtti.cpp) when auto offsetValue is calculated an access violation occurs:

`static void * FindCompleteObject(void* inptr)           // Pointer to polymorphic object
{
    // Ptr to CompleteObjectLocator should be stored at vfptr[-1]
    const auto pCompleteLocator = GetCompleteObjectLocatorFromObject(inptr);
    const auto inAddr = reinterpret_cast<uintptr_t>(inptr);
    auto pCompleteObject = inAddr - pCompleteLocator->offset;

    // Adjust by construction displacement, if any

    // We know we can read an int from inptr, because it points at pointer to vtbl.
    // Therefore we optimistically read the int here even if cdOffset is 0, in
    // order to make it legal to generate a cmov instruction.
    const auto cdOffset = pCompleteLocator->cdOffset;
    auto offsetValue = *reinterpret_cast<int *>(inAddr - cdOffset);
`

**Comment by eren-kemer** [comment]
Same issue here. Trying to Open associated contents table on Inbox and it crashes.

Tried with MDB_ONLINE and MAPI_NO_CACHE checked.

**Comment by stephenegriffin** [comment]
I know what I did - I've pulled 18.2.18154.97 while I fix this...

**Comment by stephenegriffin** [comment]
BTW - what I did was let resharper convince me to convert a ton of static_cast to dynamic_cast when MAPI objects can't deal with that. Rather than unwind all of that though, I'm gonna take this opportunity to eliminate ALL casts of MAPI objects. Might take a few days...

**Comment by stephenegriffin** [comment]
Hopefully fixed by #140 - build will be up shortly for testing

**Comment by stephenegriffin** [comment]
Try [this release](https://github.com/stephenegriffin/mfcmapi/releases/tag/18.2.18156.108).

**Comment by EinmalIM** [comment]
Fixed. Thank you!
