### ISSUE TITLE
OpenItemProp Fails

### ISSUE THREAD

**Issue by MrJG** [stephenegriffin/mfcmapi#152]
I keep getting the error message below - Not sure what it means...

Error: Failed to open message.
Code: MAPI_E_USER_CANCEL == 0x80040113
Function (null)
File c:\projects\mfcmapi\ui\dialogs\contentstable\folderdlg.cpp
Line 1657

**Comment by stephenegriffin** [comment]
What were you doing when you got this error? What version # of MFCMAPI?

**Comment by MrJG** [comment]
Hello – I was trying to export my autofill options using the 32 bit version.

I used NK3edit and found a solution.

Thanks for replying though!

John

**Comment by stephenegriffin** [comment]
ok - I'm glad you found a workaround, but I would like to do something with this report - can you tell me what version of MFCMAPI you were using and the actual action you performed that got that error?

**Comment by MrJG** [comment]
Sure – I was using

https://github.com/stephenegriffin/mfcmapi/releases/download/18.2.18160.129/MFCMAPI.exe.18.2.18160.129.zip

I had gone through logon – chosen my session, selected my email address, expanded the inbox and root, right clicked and gone to associated contents table, selected IPM.CONFIGURATION.AUTOCOMPLETE, then tried to export as UNICODE.

I followed the advice on a couple of websites that both linked back to you, the fault may be with them.


Thanks,

John

**Comment by stephenegriffin** [comment]
For my reference, this was the line that threw the error:
https://github.com/stephenegriffin/mfcmapi/blob/18.2.18160.129/UI/Dialogs/ContentsTable/FolderDlg.cpp#L1657

**Comment by MrJG** [comment]
No idea, I was following  the  script not the coding



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by ztrhgf** [comment]
I have similar problem. But my export of IPM.Configuration.Autocomplete failed with:

Error: Failed to open message.
Code: MAPI_E_USER_CANCEL == 0x80040113
Function (null)
File c:\projects\mfcmapi\ui\dialogs\contentstable\folderdlg.cpp
Line 1524

I am using MFCMAPI.exe.18.2.18169.137 and Outlook 2016 version 16.0.4639.1000. Both 32 bit.

**Comment by stephenegriffin** [comment]
Line reference for @ztrhgf is:
https://github.com/stephenegriffin/mfcmapi/blob/18.2.18169.137/UI/Dialogs/ContentsTable/FolderDlg.cpp#L1524
IE - same code.

From code examination, it looks like OpenItemProp is failing/not returning an item.

Data request: 
1. Do all your steps up to selecting the IPM.Configuration.Autocomplete message.  
2. Ctrl+D to open the Debug Viewer.  
3. In Debug flags, type: 40000140  
4. Leave the Debug Viewer open and do the export step. Get and dismiss the error.  
5. Switch back to the Debug Viewer and copy out the contents.  
6. Report the debug output back here.  
Thanks!

**Comment by ztrhgf** [comment]
Output of debug is:

0x4d94 05:44:21.819AM  06-21-2018 0x00000100: CContentsTableDlg::OpenItemProp iSelectedItem = 0x6
0x4d94 05:44:21.822AM  06-21-2018 0x00000040: Error: Failed to open message.
Code: MAPI_E_USER_CANCEL == 0x80040113
Function (null)
File c:\projects\mfcmapi\ui\dialogs\contentstable\folderdlg.cpp
Line 1524

![image](https://user-images.githubusercontent.com/2930419/41700115-3ca994b8-7527-11e8-8789-2b4a12b11691.png)

**Comment by stephenegriffin** [comment]
Very interesting that props are from row ( bottom left of your screenshot). That means you never opened the item in the first place, so it makes sense export can’t work.

**Comment by stephenegriffin** [comment]
I know what I broke now and why I couldn't repro.

**Comment by Aantczak1981** [comment]
0x26b8 07:43:53.697PM  06-21-2018 0x00000001: CSingleMAPIPropListCtrl::GetSelectedPropTag returning lpPropTag = 0x8245000A
0x26b8 07:43:56.356PM  06-21-2018 0x80000000: CFolderDlg::HandleMenu wMenuSelect = 0xA34D = 41805
0x26b8 07:43:56.357PM  06-21-2018 0x00000001: CFolderDlg::OnSaveMessageToFile 
0x26b8 07:43:59.385PM  06-21-2018 0x00000100: CContentsTableDlg::OpenItemProp iSelectedItem = 0x0
0x26b8 07:43:59.386PM  06-21-2018 0x00000001: CContentsTableListCtrl::DefaultOpenItemProp iItem = 0, bModify = 0, m_ulContainerType = 0x3
0x26b8 07:43:59.386PM  06-21-2018 0x00000001: Item being opened:
cb: 24 lpb: EF0000007BFC33755E24664F8980A8A8309DD99868151000
0x26b8 07:43:59.391PM  06-21-2018 0x00000001: CContentsTableListCtrl::DefaultOpenItemProp returning *lppProp = 00000000 and hRes = 0x0

**Comment by stephenegriffin** [comment]
Should be fixed in 18.2.18172.140
