### ISSUE TITLE
Change the One Touch Archive Button

### ISSUE THREAD

**Issue by tim5700** [stephenegriffin/mfcmapi#196]
Can I use this tool to change the behavior of the one touch archive button in Outlook & OWA?  Long story short, before this was a thing, I had a folder Mailbox\Inbox\Archive that the Archive button has been using.  I want to switch the button's behavior to move messages to Mailbox\Archive instead of Mailbox\Inbox\Archive.

Can that be accomplished with this tool?

**Comment by stephenegriffin** [comment]
I have no idea if there are any settings behind that button or if they would be stored in the mailbox.

**Comment by tim5700** [comment]
Any idea why a folder I delete using mfcmapi would keep coming back?

**Comment by stephenegriffin** [comment]
Is this any folder or a specific folder? If the latter, you’re deleting a folder that some othe piece of code thinks it needs, so it creates it when missing.

**Comment by tim5700** [comment]
Specific folder:  Mailbox\Inbox\Archive which is a folder I created roughly
ten years ago.  When MS created the default Mailbox\Archive folder with the
"Archive" button, my mail clients ended up not consistent with the behavior
or the Archive button.  Sometimes they go to the default.  Sometimes the
one I created.  I'd rather go with the default folder.  Either way I need
consistency.

**Comment by stephenegriffin** [comment]
Something to try - delete the system created archive folder, then move your folder to the location of the system one. Make sure it's a move and not a copy. That way, any cached entry IDs pointing at your folder will still work.

**Comment by tim5700** [comment]
Moved my mailbox from the cloud to on prem. 

That allowed me to use mfcmapi to delete the folder.
