### ISSUE TITLE
Logon Fails with error = MAPI_E_CALL_FAILED

### ISSUE THREAD

**Issue by rhhollin** [stephenegriffin/mfcmapi#199]
When trying to logon program fails with error 0x80004005==MAPI_E_CALL_FAILED. Neither known issue applies as I have a 64 bit version of Outlook installed and Outlook, not Windows Mail,is the default mail client. I have a stuck message sending but no message in the outbox of wither of the two accounts in Outlook. I suspect a stuck read receipt, cannot get MFCMAPIx64 started to fix the problem

**Comment by stephenegriffin** [comment]
Can you give full text of the error?

**Comment by stephenegriffin** [comment]
Thanks - what's the version # for Outlook?

**Comment by rhhollin** [comment]
MS Outlook 2016 Ver 1806 Build 10228.20134 32 bit

**Comment by stephenegriffin** [comment]
Ok. So that’s 32 bit, and you’re running the 64 bit build of MFCMAPI. As the error says, you need the 32 bit version of MFCMAPI.

**Comment by rhhollin** [comment]
Stephen - thanks for the assist, I clearly missed the sentence that said use 32 bit even if operating system is 64 bit.
