### ISSUE TITLE
help with auto complete

### ISSUE THREAD

**Issue by andy142** [stephenegriffin/mfcmapi#201]
I have an issue where I need to export the auto complete from an old PST file and import it in to a new one

I cant seem to be able select the old PST as the source file so I can copy the auto complete and paste it in to a new PST

would it be faster to run MFCMAPI on the old machine rather then fight with it on the new machine ?

**Comment by stephenegriffin** [comment]
You don't give enough information on where you're having a problem to help you here. I don't know how to interpret "can't seem to be able to select the old PST".

**Comment by andy142** [comment]
ok more info
2 pst's one old.pst one new.pst

if I load MFCMAPI on the new pc it picks up the old.pst only and there seems to be no way to make it load the new one (or was I blind)

-side note-

I did "fix" the issue by using MFCMAPI on the old Pc and exporting it to the new one  but for future updates selecting the file you want to export the auto complete might be a thing ?

**Comment by stephenegriffin** [comment]
Random PST on disk won't ever be seen until you add them to a MAPI profile. MFCMAPI only knows what's in the profile.
