### ISSUE TITLE
Auto Complete Import Error

### ISSUE THREAD

**Issue by astyron** [stephenegriffin/mfcmapi#204]
I receive the following error when go to import the autocomplete file.
![2018-08-19](https://user-images.githubusercontent.com/42528084/44318385-25386c00-a425-11e8-8026-164c47e804bc.png)

**Comment by stephenegriffin** [comment]
I don't know what steps you're following to "import the autocomplete file".

**Comment by astyron** [comment]
After deleting the Auto complete file, I select Folder, Import, MSG File and select the file. Select the load into current folder and then this error pops up.

**Comment by stephenegriffin** [comment]
That error is RPC_S_CALL_FAILED. Where are you getting this MSG file?

**Comment by astyron** [comment]
It is coming from the export feature of this software from the old computer.
