### ISSUE TITLE
MFCMAPI Fixes Temporarily But Then Reverts

### ISSUE THREAD

**Issue by WeaselSW** [stephenegriffin/mfcmapi#206]
I use MFCMAPI to change the titles of my exchange 365 accounts in Outlook.  For instance, I change the email address heading to a recognizable name.  Recently, however, the MFCMAPI has been successfully changing the account titles, but after a couple days, they revert back to the standard email address headings.  I'm assuming Microsoft released some sort of an update to not allow the headings to save, or they get overwritten by server-side updates.  Is anyone else having this issue and found a resolution?

**Comment by stephenegriffin** [comment]
You're most likely getting updated through autodiscover
