### ISSUE TITLE
No files in Root container contents for True Default Store file

### ISSUE THREAD

**Issue by LCRawls** [stephenegriffin/mfcmapi#235]
I've used mfcmapi successfully in the past, but someone else requested a read receipt and I must have accidentally hit send. I cannot get outlook 2016 messages to send any more. They sit in my outbox. When I run mfmapi (32-bit), I can see the line with the Default Store column set to True. But when I open contents table in the Root Container, everything is empty. No files. There was one there earlier that I deleted permanently when the Abort submit button did nothing. Now, nothing shows. Even the hidden folder is empty. Help!

**Comment by stephenegriffin** [comment]
The root container of a mailbox would rarely ever have anything in it. It sounds like you need to expand the root container to see the items underneath it.

**Comment by LCRawls** [comment]
My usual practice is to follow the instructions that say to open the contents table in the Root container and see what's there. It's always worked in the past. I did look at items under the root container. This morning, though it seems to be working, so I'll leave it alone for now.
