### ISSUE TITLE
Using MrMapi to clean PR_OST_OSTID

### ISSUE THREAD

**Issue by vasellivittorio** [stephenegriffin/mfcmapi#236]
Hello, 
I need to clean the PR_OST_OSTID property as written in this article:
https://support.microsoft.com/en-ie/help/3046189/you-cannot-start-outlook-in-cached-mode-or-create-a-new-cached-mode-pr

Since I will need to do it very often and I would like to automate the process I am wondering if it is possible to do the same operation using MrMapi and I wanted to know where I can find some guide/documentation to do it.

Thanks.

**Comment by stephenegriffin** [comment]
MrMAPI can't be used for this
