### ISSUE TITLE
Unable to delete a reminder

### ISSUE THREAD

**Issue by SenthilMaster** [stephenegriffin/mfcmapi#243]
Installed MCFMAPI to delete a reminder opening everytime I open Outlook (2010).

I found the reminder, but when I try to delete it (either simple delete, permanant, or hard delete), nothing is happening. The line with the reminder is still there in MCFMAPI (and still coming in outlook of course). No error message.

It seems I can edit some of its properties, but I don't know which one nor how...

Anybody can help ?
Thanks

**Comment by stephenegriffin** [comment]
There is no such thing as a reminder object. What you see in the Reminders search folder is actual appointments that have properties such that they match the criteria the reminders folder is looking for.

In other words, deleting "a reminder" is a very bad idea - you're trying to delete the actual appointment when you do that.

**Comment by SenthilMaster** [comment]
Thank you for your quick reply.

Ok maybme "reminder object" is not the correct term, When I open MFCMAPI, go to 'QuickStart > Open folders > Reminders', select my Outlook .pst file, I can see an "Instance Key", of the reminder I want to get rid of.

Just to be very clea with my issue : everytime I open Outlook, there's a reminder that pops up. I cannot open it (double click is not doing anything), nor snooze it (I get an error message : cannot find the item), I can only dismiss it. But it will show up again next time I open Outlook.
I searched for this reminder (a yearly reminder which was set up long time ago, which I deleted at some point) in my calendar but couldn't find it.

So is there a way to get rid of this reminder ?

Thanks for you help

**Comment by hapklaar** [comment]
I have the same issue with one of the appointments that keep generating reminders. I tried deling this appointment in mfcmapi, but nothing happens and the appointment is not deleted. Tried all 3 delete options, no go.

What can be done?

**Comment by pradeep3184** [comment]
Hi, 

Calendar invites no longer available on Outlook, reminders popups with overdue. unable to delete those stale invites using latest Mfcmapi Version. tried all 3 delete option it doesn't give any Error message but invite remains. please advise

**Comment by stephenegriffin** [comment]
none of these are issues with the tool MFCMAPI - they're general support questions for Outlook or an Exchange mailbox.
