### ISSUE TITLE
Double click on mailbos do not open store

### ISSUE THREAD

**Issue by nicojmb** [stephenegriffin/mfcmapi#248]
Hi, 

We need to delete corrupted rules and i follow this manual https://blogs.msdn.microsoft.com/hkong/2015/02/27/how-to-delete-corrupted-hidden-inbox-rules-from-a-mailbox-using-mfcmapi/

But when double click to mailbox nothing happen..

Here are debug when double click:

`0x2454 02:24:46.453PM  12-12-2018 0x00000001: CSingleMAPIPropListCtrl::GetSelectedPropTag returning lpPropTag = 0x0
0x2454 02:24:46.974PM  12-12-2018 0x00000001: CContentsTableListCtrl::GetNextSelectedItemNum iItem before = 0xFFFFFFFF
0x2454 02:24:46.974PM  12-12-2018 0x00000001: CContentsTableListCtrl::GetNextSelectedItemNum iItem after = 0x0
0x2454 02:24:46.975PM  12-12-2018 0x00000100: CMainDlg::OpenItemProp iSelectedItem = 0x0
0x2454 02:24:46.975PM  12-12-2018 0x00000100: CallOpenMsgStore ulFlags = 0x104
0x2454 02:24:56.756PM  12-12-2018 0x00000040: Error: 
Code: MAPI_E_FAILONEPROVIDER == 0x8004011D
Function lpSession->OpenMsgStore( ulUIParam, lpEID->cb, reinterpret_cast<LPENTRYID>(lpEID->lpb), nullptr, ulFlags, static_cast<LPMDB*>(&lpMDB))
File c:\projects\mfcmapi\mapi\mapistorefunctions.cpp
Line 38
0x2454 02:24:56.760PM  12-12-2018 0x00000001: CContentsTableListCtrl::GetNextSelectedItemNum iItem before = 0x0
0x2454 02:24:56.761PM  12-12-2018 0x00000001: CContentsTableListCtrl::GetNextSelectedItemNum iItem after = 0xFFFFFFFF`

**Comment by Tuxhedoh** [comment]
I'm having this same issue. Been working with MS on a problem. I can't open my mailbox store. I tried several things yesterday on my primary machine.  So I moved to a different machine, it worked yesterday, then when MS called me back it's not working.    I enabled the logging.  I see several errors... so it's difficult for me to tell which is relevant. 
[mfcmapi.log](https://github.com/stephenegriffin/mfcmapi/files/2672962/mfcmapi.log)

**Comment by stephenegriffin** [comment]
OpenMsgStore is failing with MAPI_E_FAILONEPROVIDER - this is a MAPI bug, not an MFCMAPI bug.

**Comment by Tuxhedoh** [comment]
Do you have a suggestion on how to troubleshoot or escalate? At this point the Office support team had told me unless mfcmapi can work they have no other troubleshooting steps for me. I'm not trying to make this your problem, just looking for next steps.

**Comment by stephenegriffin** [comment]
Tell them they need to escalate and loop me in - I can investigate it internally (I'm their escalation path).

**Comment by Tuxhedoh** [comment]
Thanks a ton Stephen.
Just got off the phone with them. They made it sound like they wouldn't be able to escalate or loop you in, but they said they'd try.   This is my MS Ticket #:12353050

**Comment by nicojmb** [comment]
We have open the issue from 8 days and microsoft can not fixit ([Ticket #:12429454]).

Can you support us, we need delete a hidden rule beacusae mail items are deleted with this message "Motivo: [Stage: DeliverPreDelivery];StoreDriver.Rules; message is deleted by mailbox rules"

And MCFMAPI not open mailboxsotore, we can pay whatever the amount is, it the mailbox from uor CEO and very important.
