### ISSUE TITLE
MFCMAPI freezes after double clicking mailbox

### ISSUE THREAD

**Issue by lifuhuang** [stephenegriffin/mfcmapi#258]
When I double clicked my mailbox, the program freezes for like 30 seconds and then silently become responding again but nothing happens (the store is not opened).

There were no error messages being shown. Sometimes reboot my machine for A FEW times might solve the problem, but very soon the issue comes back again.

Could you please provide suggestions on how I can diagnose the problem and be able to open the store?

**Comment by stephenegriffin** [comment]
What version of MFCMapi are you testing with?

**Comment by lifuhuang** [comment]
18.2.18328.557

**Comment by stephenegriffin** [comment]
Try the current build

**Comment by lifuhuang** [comment]
Hi @stephenegriffin , after using the latest build, now it starts showing error message after double clicking the mailbox:

> Error: 
> Code: MAPI_E_FAILONEPROVIDER == 0x8004011D
> Function lpSession->OpenMsgStore( ulUIParam, lpEID->cb, reinterpret_cast<LPENTRYID>(lpEID->lpb), nullptr, ulFlags, static_cast<LPMDB*>(&lpMDB))
> File c:\projects\mfcmapi\mapi\mapistorefunctions.cpp
> Line 40

**Comment by stephenegriffin** [comment]
Solved by #257
