### ISSUE TITLE
Exception while deleting a corrupted Reminders folder

### ISSUE THREAD

**Issue by ejalal** [stephenegriffin/mfcmapi#264]
Hi guys

I have corrupted reminders in outlook 2010 since a very long time and I can't dismiss or delete them.

I followed this tutorial https://support.microsoft.com/en-us/help/2949811/you-can-t-successfully-dismiss-calendar-reminders-in-outlook, but still can't delete the reminders folder as suggested.

I get this error, with or without Hard delete checked.

Warning: 
Code: MAPI_W_PARTIAL_COMPLETION == 0x00040680
Function lpParentFolder->DeleteFolder( lpItemEID->cb, reinterpret_cast<LPENTRYID>(lpItemEID->lpb), lpProgress ? reinterpret_cast<ULONG_PTR>(m_hWnd) : NULL, lpProgress, ulFlags)
File c:\projects\mfcmapi\ui\dialogs\hierarchytable\msgstoredlg.cpp
Line 788

**Comment by stephenegriffin** [comment]
That's not an exception - the provider wasn't able to complete your request.

**Comment by LockTar** [comment]
I have the exact problem. Followed resolution 2 of this [article](https://learn.microsoft.com/en-us/exchange/troubleshoot/calendars/cannot-dismiss-outlook-calendar-reminders#resolution-2). Got the same message. The folder is gone but the reminder are still there.

Using outlook version:
Microsoft® Outlook® for Microsoft 365 MSO (Version 2301 Build 16.0.16026.20002) 64-bit

Do you have another solution?

**Comment by LockTar** [comment]
I also tried Resolution 3 of the article which removed the reminders until I restarted outlook and then they reappeared.
The reminders are all from shared outlook.com (family) calendars.
