### ISSUE TITLE
Cannot input credential programmatically for Exchange365 profile

### ISSUE THREAD

**Issue by supcxc** [stephenegriffin/mfcmapi#276]
Hi Steve,

I'm working on a MAPI program for Exchange 365 that is running as background service without GUI interaction. For now I can only use Outlook GUI to pop up the authentication dialog and input the user name and password manually. 

I'm looking for a way to input credential (mailbox user password) programmatically for Exchange365 profile. But it seems [you said there's no way to do so in 2015](https://blogs.msdn.microsoft.com/dvespa/2014/01/17/how-to-create-an-outlook-profile-for-office-365/).

I'd like to know if there's a way to do this in code now? It seems strange that MAPI API does not provide a logon function to input user credential. 

Thanks.
Simon

**Comment by stephenegriffin** [comment]
Not an issue with MFCMAPI
