### ISSUE TITLE
Cannot delete corrupt OOF rules from recoverable items folder

### ISSUE THREAD

**Issue by xxJoo** [stephenegriffin/mfcmapi#278]
Thanks a lot for everyone who will comment and support here.

I got an issue when try to move user mailbox from one DB to another DB in Exchange 2010, with error event 8533 in application log.

_"A problem occurred while getting the properties for the **automatic reply message** from username.
 Error code: -2147221233.

 Try to clear the rules or run ISINTEG to check for any problem in the database "xxxxxxxx". "_

Then I tried to export this mailbox to an PST, also failed, and from detail log it showing below error.

FailureCode                   : -2147023232
FailureType                   : MapiExceptionPartialCompletion
FailureSide                   : Source
Message                       : Error: MapiExceptionPartialCompletion: Unable to copy to target. (hr=0x40680, ec=0)

FailureTimestamp              : 28/03/2019 04:37:56
FailureContext                : --------
                                Operation: ISourceFolder.CopyTo
                                OperationSide: Source
                                Primary (86a44420-bfbf-4331-bb6a-324fee607156)
                                PropTags: [ContainerContents; FolderAssociatedContents; ContainerHierarchy; DisplayName
                                ; RulesTable; 1071710466]
                                --------
                                **Folder: '/Recoverable Items/Deletions'**, entryId [len=46, data=000000006FCCABB5DAAA9C4E9
                                34AE9DEAA3C9E6A010090D51718D91045459604BDDEF18A1BB900000000A3AD0000], parentId [len=46,
                                 data=000000006FCCABB5DAAA9C4E934AE9DEAA3C9E6A010090D51718D91045459604BDDEF18A1BB900000
                                000A3A80000]

Then I use MFCMAPI(**x86 version 19.2.19058.831**) to open user mailbox, go to /Recoverable Items/Deletions, got below error when I first click "Deletions" folder:
Error: GetProps(NULL) failed
Code: MAPI_E_BAD_VALUE == 0x80040301
Function (null)
File c:\projects\mfcmapi\propertybag\mapiproppropertybag.cpp
Line 80

Then I right click Open associated contents table, I did find there are 10 rules related to Microsoft Exchange OOF Assistant and MSFT:TDX OOF Rules, all of their Message Class is IPM.Rule.Message.

**Got below error when try to hard delete the rules.**
Warning: 
Code: MAPI_W_PARTIAL_COMPLETION == 0x00040680
Function m_lpFolder->DeleteMessages( lpEIDs, lpProgress ? reinterpret_cast<ULONG_PTR>(m_hWnd) : NULL, lpProgress, ulFlag)
File c:\projects\mfcmapi\ui\dialogs\contentstable\folderdlg.cpp
Line 678

**Below is the debug details when use Debug flags:40000140**
0x20e4 07:05:05.607AM  03-28-2019 0x00000100: CContentsTableDlg::OpenItemProp iSelectedItem = 0x4
0x20e4 07:05:05.904AM  03-28-2019 0x40000000: Function call: c:\projects\mfcmapi\core\mapi\mapifunctions.cpp@119: lpMDB->OpenEntry(cbEntryID, lpEntryID, lpInterface, ulFlags, &ulObjType, &lpUnk)
0x20e4 07:05:06.185AM  03-28-2019 0x40000000: Function call: c:\projects\mfcmapi\core\mapi\mapifunctions.cpp@2406: HrGetOneProp(lpMAPIProp, g_DisplayNameProps[i], &lpProp)
0x20e4 07:05:06.185AM  03-28-2019 0x00000040: Error: 
Code: MAPI_E_NOT_FOUND == 0x8004010F
Function HrGetOneProp(lpMAPIProp, g_DisplayNameProps[i], &lpProp)
File c:\projects\mfcmapi\core\mapi\mapifunctions.cpp
Line 2406
0x20e4 07:05:06.467AM  03-28-2019 0x40000000: Function call: c:\projects\mfcmapi\core\mapi\mapifunctions.cpp@2406: HrGetOneProp(lpMAPIProp, g_DisplayNameProps[i], &lpProp)
0x20e4 07:05:06.482AM  03-28-2019 0x00000040: Error: 
Code: MAPI_E_NOT_FOUND == 0x8004010F
Function HrGetOneProp(lpMAPIProp, g_DisplayNameProps[i], &lpProp)
File c:\projects\mfcmapi\core\mapi\mapifunctions.cpp
Line 2406
0x20e4 07:05:06.497AM  03-28-2019 0x40000000: Function call: c:\projects\mfcmapi\core\mapi\mapifunctions.cpp@2406: HrGetOneProp(lpMAPIProp, g_DisplayNameProps[i], &lpProp)
0x20e4 07:05:06.497AM  03-28-2019 0x00000040: Error: 
Code: MAPI_E_NOT_FOUND == 0x8004010F
Function HrGetOneProp(lpMAPIProp, g_DisplayNameProps[i], &lpProp)
File c:\projects\mfcmapi\core\mapi\mapifunctions.cpp
Line 2406
0x20e4 07:05:06.779AM  03-28-2019 0x40000000: Function call: c:\projects\mfcmapi\core\mapi\mapifunctions.cpp@306: lpMAPIProp->GetPropList(ulFlags, &lpTags)
0x20e4 07:05:07.061AM  03-28-2019 0x40000000: Function call: c:\projects\mfcmapi\core\mapi\mapifunctions.cpp@322: lpMAPIProp->GetProps(lpTags, ulFlags, lpcValues, lppPropArray)
0x20e4 07:05:08.873AM  03-28-2019 0x40000000: Function call: c:\projects\mfcmapi\core\mapi\mapistorefunctions.cpp@428: lpMAPISession->GetMsgStoresTable(0, &pStoresTbl)
0x20e4 07:05:08.873AM  03-28-2019 0x40000000: Function call: c:\projects\mfcmapi\core\mapi\mapistorefunctions.cpp@445: HrQueryAllRows( pStoresTbl, LPSPropTagArray(&sptEIDCol), &sres, nullptr, 0, &pRow)
0x20e4 07:05:08.873AM  03-28-2019 0x00000100: CallOpenMsgStore ulFlags = 0x104
0x20e4 07:05:09.810AM  03-28-2019 0x40000000: Function call: c:\projects\mfcmapi\core\mapi\mapistorefunctions.cpp@41: lpSession->OpenMsgStore( ulUIParam, lpEID->cb, reinterpret_cast<LPENTRYID>(lpEID->lpb), nullptr, ulFlags, static_cast<LPMDB*>(&lpMDB))
0x20e4 07:05:13.796AM  03-28-2019 0x40000000: Function call: c:\projects\mfcmapi\ui\dialogs\contentstable\folderdlg.cpp@678: m_lpFolder->DeleteMessages( lpEIDs, lpProgress ? reinterpret_cast<ULONG_PTR>(m_hWnd) : NULL, lpProgress, ulFlag)
0x20e4 07:05:13.796AM  03-28-2019 0x00000040: Warning: 
Code: MAPI_W_PARTIAL_COMPLETION == 0x00040680
Function m_lpFolder->DeleteMessages( lpEIDs, lpProgress ? reinterpret_cast<ULONG_PTR>(m_hWnd) : NULL, lpProgress, ulFlag)
File c:\projects\mfcmapi\ui\dialogs\contentstable\folderdlg.cpp
Line 678

**Comment by EinmalIM** [comment]
Did you try to set -BadItemLimit 1 (or higher) in your new-moverequest call, when you initiate the mailbox move? Maybe that fixes your issue by ignoring the problematic item(s).

**Comment by xxJoo** [comment]
> Did you try to set -BadItemLimit 1 (or higher) in your new-moverequest call, when you initiate the mailbox move? Maybe that fixes your issue by ignoring the problematic item(s).

Thanks EinmaIIM, yes, I even tried to set baditemlimit to 1000 and still no lock as the move request always failed once start.
I'm able to export mailbox to PST with -excludeDump, but always failed when include dump.
