### ISSUE TITLE
outlook 2013 / Windows 7 - mfcmapi tool cannot delete message stuck in outbox with 75mb attachment

### ISSUE THREAD

**Issue by brendanruff** [stephenegriffin/mfcmapi#28]
Hi

Looks like I have managed to outwit the tool. I attached 75mb's to a message and both unsubmit and delete attachment fail (see below). Any ideas ?

Thanks
Brendan

Error: 
Code: MAPI_E_UNABLE_TO_ABORT == 0x80040114
Function lpMDB->AbortSubmit( lpMessageEID->cb, reinterpret_cast<LPENTRYID>(lpMessageEID->lpb), NULL)
File Dialogs\ContentsTable\FolderDlg.cpp
Line 2045

**Comment by stephenegriffin** [comment]
All MAPI can do is ask that an operation be performed. It's up to the server (or perhaps the PST) to perform the operation. So this isn't a bug in MFCMAPI. If you're working online you might look into [Remove-Message](https://technet.microsoft.com/en-us/library/aa996371(v=exchg.160).aspx) or [Suspend-Message](https://technet.microsoft.com/en-us/library/aa997457(v=exchg.160).aspx).

**Comment by brendanruff** [comment]
Hi Stephen

 

Thanks for the reply. OK so the problem is Outlook’s internal server. Any ideas how to get rid of the email manually by editing the pst file or some such ? Maybe Windows safe mode will fix it to prevent services running etc ? Something like this ?

 

The stuck email is a pain as it prevents emails going out unless you kill the Outlook process and restart in which case Outlook seems to process the emails in order of size starting with the smallest thankfully !!

 

Thanks

 

Brendan
