### ISSUE TITLE
Need instructions on how to proper install github version

### ISSUE THREAD

**Issue by 37west** [stephenegriffin/mfcmapi#286]
Unable to find .exe after downloading from github, having difficulty finding documentation on how to properly install after downloading. The last version I tried had no issue from http://mfcmapi.codeplex.com

**Comment by stephenegriffin** [comment]
The latest release is here:
https://github.com/stephenegriffin/mfcmapi/releases/tag/19.0.19115.01
and you want to download the zip and extract the exe from it. There's nothing to install. This is exactly how it worked on codeplex.
