### ISSUE TITLE
Icons looks big in the latest version 17.0.17033.02

### ISSUE THREAD

**Issue by AlexanderSerashov** [stephenegriffin/mfcmapi#29]
![bigicons2](https://cloud.githubusercontent.com/assets/8812670/22935594/1275e97e-f2e4-11e6-80cf-b48049a1cb31.png)
![bigicons](https://cloud.githubusercontent.com/assets/8812670/22935593/127207aa-f2e4-11e6-9642-f54b2ec56026.png)

**Comment by stephenegriffin** [comment]
This has me baffled.  I'm certainly not doing it on purpose, and it doesn't repro on any machine I've tried it on. If anyone has any ideas I'm open to suggestions.

**Comment by stephenegriffin** [comment]
This page helped in understanding the bug:
https://msdn.microsoft.com/en-US/library/mt622670.aspx
I had doubled my image size for my own high DPI system, but managed not to test on regular DPI.
