### ISSUE TITLE
trying to import Quick Steps but no folder to import to

### ISSUE THREAD

**Issue by kennytil** [stephenegriffin/mfcmapi#290]
hi,

i've exported my quick steps from one mailbox but when i try to restore them to another mailbox, there's no Quick Steps Settings folder to import into
![image](https://user-images.githubusercontent.com/51022826/58369298-4ec07f80-7ef0-11e9-89e8-7bdb4c85fad3.png)

any advice?

TIA

K

**Comment by stephenegriffin** [comment]
This is not the proper forum for discussing random articles that give steps to perform in mfcmapi. You should be discussing those issues with the authors of those articles.
