### ISSUE TITLE
Deleted Reminders folder but returns automatically

### ISSUE THREAD

**Issue by Jamayadje** [stephenegriffin/mfcmapi#292]
Hi,

I tried to delete the reminders folder for 1 user, but when we press F5 it returns automatically.

Closed Outlook, even set mobile devices with in flightmode so they do not connect to Exchange.

Need this since the user is not receiving any reminders after migrating his mailbox from Exchange 2010 to 2016 (and back because of this issue).

Any ideas?

Thanks in advance, Jack

**Comment by stephenegriffin** [comment]
The reminders folder is gonna get recreated by Outlook or Exchange. They use it.
