### ISSUE TITLE
Question about "well known" database guid

### ISSUE THREAD

**Issue by tcataldo** [stephenegriffin/mfcmapi#293]
Looking at this unit test expected output I have a question about the following database guid.

https://github.com/stephenegriffin/mfcmapi/blob/48c2a6becf0248076848025c3711cb1b2eb7ee45/UnitTest/SmartViewTestData/Out/4-eid-out10.dat#L5

I can't find it inside exchange protocols, windows protocols or office protocols but it seems like a constant we can find in our outlook registries (Perf/RoamingStreamsCache). When outlook cancels a search done with MS-OXWSOLPS it re-submits the search on a folder with this database guid.

Can you point me to what this database guid refers to or why you added a test for this specific message object entry id ?

**Comment by stephenegriffin** [comment]
>why you added a test for this specific message object entry id ?
I grabbed a random eid from my mailbox to build a test around. :) The data for that test has been in my private tests for years so I don't really know what it pointed to.
