### ISSUE TITLE
Edit as stream > Unicode fails on PR_SUBJECT_W with MAPI_E_NO_ACCESS

### ISSUE THREAD

**Issue by EinmalIM** [stephenegriffin/mfcmapi#324]
I use MFCMAPI (19.0.19115.01) and Outlook Office ProPlus 2016 (version 1909 64-bit) connected to a server mailbox on Exchange 2016 on-prem. Tried the following with and without Exchange Cache Mode, makes no difference:

When I select any single message to show its properties and use the "Edit as stream > Unicode..." from the context menu of the PR_SUBJECT_W property I get the property editor dialog showing this error:

Could not open stream interface.
Error Code: MAPI_E_NO_ACCESS == 0x80070005

No problems to open other PT_UNICODE properties as stream.

Any idea, why I cannot open PR_SUBJECT_W as stream?

**Comment by stephenegriffin** [comment]
This is normal - not all string properties support streams. Subject is short enough never to need it
