### ISSUE TITLE
When MDB_ONLINE flag and MAPI_NO_CACHE flag is used cant open store

### ISSUE THREAD

**Issue by dahager** [stephenegriffin/mfcmapi#328]
When i use MDB_ONLINE flag and MAPI_NO_CACHE flag i am not able to open the Store of a mailbox that is hosted on exchange online.

Without flags -> works
Outlook -> works

funny thing, different mailbox on same tenant works

**Comment by stephenegriffin** [comment]
this is not a bug in mfcmapi
