### ISSUE TITLE
PR_PST_PATH issue

### ISSUE THREAD

**Issue by thims** [stephenegriffin/mfcmapi#33]
Machine:

Windows 10 x64 version 10.0.14393 (with all updates installed on 27 Mar, 2017).
Outlook 2016 x86 version 1702 (build 7870.2024)

The issue:

When adding PST file using MFCMAPI, PR_PST_PATH gets weird values depending on PST full path.

Prerequisites:

1. Put a PST file on a local drive. In my case, in the root of C:\.
1. Create a local SUBST'ed drive and put a PST file there. In my case, S: substed to C:\temp.
2. Create a network mapped drive and put a PST file there. In my case, N: mapped to \\\\server\share

Steps to reproduce in MFCMAPI:

1. Select Profile -> Show profiles and select the required profile.
2. Select Actions -> Services -> Add PST... and select the C:\file.pst. Click OK.
3. Select Actions -> Services -> Add PST... and select the S:\file.pst. Click OK.
4. Select Actions -> Services -> Add PST... and select the N:\file.pst. Click OK.
5. Select Actions -> Open profile.
6. Select the service for the first added PST file and open it. Select the appropriate provider. Look at the PR_PST_PATH property. It's "\\\\?\C:\file.pst".
7. Select the service for the second added PST file and open it. Select the appropriate provided. Look at the PR_PST_PATH property. It's "\\\\?\C:\temp\file.pst".
8. Select the service for the third added PST file and open it. Select the appropriate provider. Look at the PR_PST_PATH property. It's "\\\\?\UNC\server\share\file.pst".

Expected behavior (when opening PST files right in Outlook using File -> Open -> Open Outlook Data  File):

1. PR_PST_PATH for the "C:\file.pst" is "C:\file.pst".
2. PR_PST_PATH for the "S:\file.pst" is "S:\file.pst".
3. PR_PST_PATH for the "N:\file.pst" is "N:\file.pst".

As you can see, when adding PST using MFCMAPI, mapped and substed drives are being resolved to their original locations. All other local files prefixed with "\\\\?\\".

Why is that? And how to fix it?

**Comment by eesheesh** [comment]
`\\?\` is a [prefix used in Windows](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx) to allow longer paths, DOS reserved names (e.g. AUX, CON), and other things.

You should be able to open the files with this prefix without issue. In most cases, it's even desired.

**Comment by thims** [comment]
@eesheesh I know what this prefix is for. But in this case it's completely undesired. Because may programs rely on PST full path. But the main issue is not the \\\\?\\ prefix. The main issue is that you can't use SUBSTed and Network Mapped drives now for some reason: it just resolves them to original location and this is the major issue.

**Comment by stephenegriffin** [comment]
I doubt this is MFCMAPI's doing - have you tried to repro in Outlook?

**Comment by thims** [comment]
As I said before, in Outlook everything is ok. So, if I open the PST in Outlook using File -> Open -> Open Outlook Data File then I get correct paths.

**Comment by stephenegriffin** [comment]
I still suspect this is an Outlook issue - they've been messing with PST paths recently. You're testing with 1702 - do you repro with other branches? Most notably, do you repro with Insider Fast or Slow?

**Comment by thims** [comment]
Both with latest Office 2016 (not Office 365) and Office 365 Insider Fast.

**Comment by stephenegriffin** [comment]
I've confirmed with the dev that the change that caused this was backed out. Lemme know if you still repro after the next Insider Fast update.

BTW - as part of this work, dev did discover some older network storage devices really don't work right and caused [GetFinalPathNameByHandle](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364962(v=vs.85).aspx) to fail. Net effect is PSTs can't work on those devices. However, since we never supported PST on a network anyway, we're not really worried about that. :)
