### ISSUE TITLE
"MAPI_E_INTERFACE_NOT_SUPPORTED == 0x80004002" when trying to retrieve Inbox rules

### ISSUE THREAD

**Issue by James-potonil340** [stephenegriffin/mfcmapi#330]
"MAPI_E_INTERFACE_NOT_SUPPORTED == 0x80004002" when trying to retrieve Inbox rules

Hi Stephen, and thank you for sharing such a useful tool !

Here is my issue:
When I try  to retrieve Inbox rules from an exchange mailbox, I get the following error :

Error: 
Code: MAPI_E_INTERFACE_NOT_SUPPORTED == 0x80004002
Function lpMAPIProp->OpenProperty( ulPropTag, const_cast<LPGUID>(&IID_IExchangeModifyTable), 0, MAPI_DEFERRED_ERRORS, reinterpret_cast<LPUNKNOWN*>(&lpExchTbl))
File c:\projects\mfcmapi\ui\dialogs\mfcutilityfunctions.cpp
Line 322

What I did was:
1. Launch MFCMAPI
2. Session -> logon
3. QuickStart -> Inbox Rules

My setup :

Exchange Server 2007 SP3, UR21 (yes, I know...)
Client is Outlook 2013 x86
MFCMAPI 19.2.19207.938

What am I missing here ?
James

**Comment by stephenegriffin** [comment]
no repro
