### ISSUE TITLE
Cannot Hard Delete Corrupted Folder

### ISSUE THREAD

**Issue by christantoan** [stephenegriffin/mfcmapi#34]
Hi,

I have a corrupted folder in my account. It cannot be deleted from Outlook normally so I resorted to MFCMAPI. Problem is, while I can delete the folder normally, it will come back some times later. That's why I decided to try with the hard delete option, but it gives me this error after clicking OK and the folder is not deleted.
![image](https://cloud.githubusercontent.com/assets/7300310/24538482/b9c52ec4-15e9-11e7-8649-19b47be5481f.png)
Thank you

**Comment by stephenegriffin** [comment]
Hard delete isn't supported by every store implementation. MFCMAPI does allow you to attempt things that stores will refuse to do. This is not a bug in MFCMAPI.
