### ISSUE TITLE
MAPILogonEx failure

### ISSUE THREAD

**Issue by czlitony** [stephenegriffin/mfcmapi#349]
@stephenegriffin  In our product, we sometimes encounter MAPILogonEx failure problems.
The calling is
```
FLAGS flFlags = MAPI_NEW_SESSION | MAPI_EXTENDED | MAPI_TIMEOUT_SHORT | MAPI_EXPLICIT_PROFILE|MAPI_UNICODE;
HRESULT hResult = MAPILogonEx(0, /*strDefaultProfile.GetBuffer(0)*/ "Outlook", NULL, flFlags, &m_lpSession);
```
The error is:
_Mapi logon failed, hr=0x80004005_

If try it again, it will succeed. Is MAPILogonEx unstable? Do you know the reason why MAPILogonEx fails sometimes?

**Comment by stephenegriffin** [comment]
this is not an mfcmapi issue
