### ISSUE TITLE
New binary download solution

### ISSUE THREAD

**Issue by stephenegriffin** [stephenegriffin/mfcmapi#35]
Codeplex going away:
https://blogs.msdn.microsoft.com/bharry/2017/03/31/shutting-down-codeplex/

**Comment by eesheesh** [comment]
I'd suggest the releases feature on GitHub.

**Comment by stephenegriffin** [comment]
Ah - thanks - I hadn't seen the releases tab before. Looks very similar to releases on codeplex. Just gotta migrate my release scripts

**Comment by stephenegriffin** [comment]
Fixed with c70774cd7cc663e96e8a46b025200c603c5eaf46
