### ISSUE TITLE
Global address list is empty

### ISSUE THREAD

**Issue by UKurze** [stephenegriffin/mfcmapi#350]
When I open an Exchange Online mailbox with mfcmapi, nothing is displayed in the global address list.

The MAPI call IAddrBook::GetDefaultDir returns "Offline Addressbook" without entries and not "Global Address list".

Outlook shows entries in the address book just like Outlook-Spy.

This only happens if the Outlook Office 365 client is installed. 
If I use Outlook 2016/2019 everything is fine and addressbook entries are displayed correctly in global address list with mfcmapi.

The MAPI call IAddrBook::GetDefaultDir returns "Offline Addressbook" without entries and not "Global Address list".

**Comment by stephenegriffin** [comment]
try opening the hierarchy instead

**Comment by UKurze** [comment]
I did that.
In the hierarchy, only the Offline Address Book is displayed (see attached file).
![OnlyOAB](https://user-images.githubusercontent.com/62990486/78329318-a3f20680-7581-11ea-9da4-8f2038069545.png)

**Comment by UKurze** [comment]
I've solved it. 
If I use Modern Authentication, I get the Global Address List with all entries.
It seems that the address book provider ( from Office 365 client) does not work with Basic Authentication (RegKey EnableADAL=0).

![GAL](https://user-images.githubusercontent.com/62990486/78330207-bb31f380-7583-11ea-934b-c0a1601a84be.png)
