### ISSUE TITLE
Add Contributing file

### ISSUE THREAD

**Issue by stephenegriffin** [stephenegriffin/mfcmapi#37]
https://github.com/blog/1184-contributing-guidelines

**Comment by desjarlais** [comment]
I've started a generic template as a starting file, you want me to do a pull or should the file just get added directly to the master and we can add to it as needed from there?

**Comment by stephenegriffin** [comment]
Do a PR to master and we can review it - thanks!

**Comment by stephenegriffin** [comment]
Thanks!
