### ISSUE TITLE
Batch .eml export, defining export settings only once for all messages

### ISSUE THREAD

**Issue by AndreasKri** [stephenegriffin/mfcmapi#392]
Hi Stephen,
great software you have made. A suggestion to improve:
I am using an export to .eml (using IConverterSession). When I select several messages to export, the setting window appear, where I only check the option "Pass Address Book To Converter" and hit Enter:
![image](https://user-images.githubusercontent.com/68102607/87130637-8379cc80-c293-11ea-866c-e9665069a9df.png)

Unfortunately, it appears, that there is no way to use the setting for all messages, so I have to check the box and hit Enter for every message.

Is it feasible to add kind of default setting, or a a checkbox like " OK, for all", which would take the settings from first window and apply them for all other messages without prompts?

That would speed up my work greatly.

Best regards
Andreas Krieger

**Comment by stephenegriffin** [comment]
I can look at this - have you tried out mrmapi.exe? It can be used for batch file exports...

**Comment by AndreasKri** [comment]
Hi Stephen,
no, not yet. Wasn't even aware about this tool. Will look at it and try out out tomorrow. A quick search revealed, that it is a command line tool.

**Comment by stephenegriffin** [comment]
Yep - purpose is for batch file exploration (read only)

**Comment by AndreasKri** [comment]
So had a try today, with partly success.
First I tried to convert isolated .msg files in the same folder where MrMapi.exe is being:
`MrMAPI -MIME -Input "Message1.msg" -Output "Message1.eml" -Ad
`
works just fine!

Problematic part:
when the filename consist german special characters, like ä,ö,ü and ß it doesn't work:
![image](https://user-images.githubusercontent.com/68102607/87312103-6ad21680-c520-11ea-9375-ff9c8a1bac2d.png)
Although the final message " File converted successfully." appeared - in fact no file appears in the folder.

Compared to successfull example (with no special characters in filename), Nothing appears after Input File: (marked red)
Apparently, because the special character in that example was on the first place. I have then tested with other filename, where the special character appears at the end or in the middle:
it turned out, the input filename is processed correctly until special character:
![image](https://user-images.githubusercontent.com/68102607/87312521-f5b31100-c520-11ea-916d-51b498bd0488.png)

I have tried to change codepage before: chcp 1252 and 65001 (UTF-8), but still no luck.




Another approach would be to grab the messages directly from the inbox, convert them and store on local folder. (Similar as with MFCMAPI, where I first Logon with "Outlook" Profile, chose the inbox/pst opened in Outlook, and take the right subfolder within the mailbox). 
But I didn't figured out the right syntax for the options.

**Comment by stephenegriffin** [comment]
Working on the unicode issue in #394

**Comment by AndreasKri** [comment]
Great!

looking forward to updated release. Meanwhile I have created a workaround which replaces the troublesome characters with valid equivalents and pass them to MrMapi:

`setlocal enableDelayedExpansion
::Obtain .msg files from store by Entry ID (which can be found with MFCMAPI) @13 is inbox
MrMAPI.exe -Contents -Profile Outlook -Folder "#0000000038A1BB100....A0000000000\@13\In Bearbeitung AK\abzulegen" -Ms

::Delete CONTENTS_TABLE.xml und FOLDER_PROPS.xml
del Folder_Props.xml CONTENTS_TABLE.xml 

:: replace long ID's in filename by running number, should subject of several messages be the same 
set /a "runnumber=0"
:neustart
ren *_00000* *_%runnumber%.*
if errorlevel 1 set /a runnumber = runnumber+1 & goto neustart

:: Replace special character by valid equivalents
set string1=ü
set string2=ue
for %%F in (*%string1%*.msg) do (
  set "filename=%%F"
  ren "!filename!" "!filename:%string1%=%string2%!"
)

set string1=ö
set string2=oe
for %%F in (*%string1%*.msg) do (
  set "filename=%%F"
  ren "!filename!" "!filename:%string1%=%string2%!"
)

set string1=ä
set string2=ae
for %%F in (*%string1%*.msg) do (
  set "filename=%%F"
  ren "!filename!" "!filename:%string1%=%string2%!"
)

set string1=ß
set string2=ss
for %%F in (*%string1%*.msg) do (
  set "filename=%%F"
  ren "!filename!" "!filename:%string1%=%string2%!"
)

set string1=Ü
set string2=Ue
for %%F in (*%string1%*.msg) do (
  set "filename=%%F"
  ren "!filename!" "!filename:%string1%=%string2%!"
)

set string1=Ö
set string2=Oe
for %%F in (*%string1%*.msg) do (
  set "filename=%%F"
  ren "!filename!" "!filename:%string1%=%string2%!"
)

set string1=Ä
set string2=Ae
for %%F in (*%string1%*.msg) do (
  set "filename=%%F"
  ren "!filename!" "!filename:%string1%=%string2%!"
)

::convert all .msg files into .eml (with passing AddressBook
for %%f in (*.msg) do MrMAPI.exe -MIME -Input "%%f" -Output "%%f.eml" -Ad

::delete all .msg files
del *.msg

::remove .msg prior to .eml file extension
set string1=.msg.eml
set string2=.eml
for %%F in (*%string1%*) do (
  set "filename=%%F"
  ren "!filename!" "!filename:%string1%=%string2%!"
)`

[Obtain and convert.bat.txt](https://github.com/stephenegriffin/mfcmapi/files/4917330/Obtain.and.convert.bat.txt)
