### ISSUE TITLE
Change subfolder hidden attributes if inherited from a system folder

### ISSUE THREAD

**Issue by jeffducasse** [stephenegriffin/mfcmapi#395]
I have a user that has important data migrated to a folder that is hidden by default.  After migration the folders put into the folder all are hidden.  Unhiding the folder temporarily does not unhide the users folder.  How can this setting be propagated or is there a way to move the folders to a user created folder easily and will that update the PR_ATTR_Hidden attribute on all folders.

**Comment by stephenegriffin** [comment]
Not an mfcmapi bug or feature request
