### ISSUE TITLE
EML to MSG conversion not working

### ISSUE THREAD

**Issue by kansasdev** [stephenegriffin/mfcmapi#4]
I have been using mrmapi successfully for almost two years with Outlook 2013.
Unfortunately after migrating to Outlook 2016 or just after some updates to Outlook 2016 (I don't know exactly when it has started happening but I think it was a month ago) mrmapi stopped working and my project on github (mailsync) is useless because I can't do conversion from EML to MSG (outlook format).
When I invoke mrmapi (with Outlook 2016 x86 installed), with following parameters (-Ma -i input.eml -o output.msg -Cc CCSF_SMTP) I am receiving following error "MAPI <-> MIME converter not found. Perhaps Outlook is not installed.".
And small unreadable for Outlook file is being saved to drive.

When I invoke EML to MSG conversion from GUI (MFCMAPI), I am receiving three message boxes:
"Error: IConverterSession not found. This interface is only supported by Outlook 2003 and higher.
Code: REGDB_E_CLASSNOTREG == 0x80040154
Function CoCreateInstance(CLSID_IConverterSession, NULL, CLSCTX_INPROC_SERVER, IID_IConverterSession, reinterpret_cast<LPVOID*>(&lpConverter))
File MapiMime.cpp
Line 27"
second:
"Error: 
Code: REGDB_E_CLASSNOTREG == 0x80040154
Function ImportEMLToIMessage( lpszEMLFile, pMessage, ulConvertFlags, bApply, hCharSet, cSetApplyType, lpAdrBook)
File MapiMime.cpp
Line 173"
third:
"Error: 
Code: REGDB_E_CLASSNOTREG == 0x80040154
Function ConvertEMLToMSG( emlfile.c_str(), msgfile.c_str(), ulConvertFlags, bDoApply, hCharSet, cSetApplyType, lpAdrBook, bUnicode)
File Dialogs\ContentsTable\MainDlg.cpp
Line 1723"

It happens both on newest version of Your software (November 2016) and on older versions as well.
Has someone report such errors?
Maybe it is business decision to stop supporting conversions in newest Outlook version (such functionality has been working fine with previous outlook versions)? It would be very sad decision.

**Comment by kansasdev** [comment]
Workaround is to install Outlook 2013 along with Outlook 2016 - definitely not convenient. Maybe you could discover which part of software is directly needed and why it has been removed from newest version

**Comment by stephenegriffin** [comment]
Nothing was removed - this is a known issue with Outlook installed via Click To Run. The interfaces MFCMAPI needs are there, but they're not registered. If they were registered, the side-by-side scenario kansasdev offers would not only not work, but one of the Outlook's would constantly crash.

**Comment by kansasdev** [comment]
Dear sir

I am still having problems with above process. I have installed Office 2016 32 bits via Click 2 Run and added some data to registry like shown here [https://blogs.msdn.microsoft.com/stephen_griffin/2014/04/21/outlook-2013-click-to-run-and-com-interfaces/](url).My registry looks like this:
`rem IConverterSession
reg copy HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\REGISTRY\MACHINE\Software\Classes\Wow6432Node\CLSID\{4E3A7680-B77A-11D0-9DA5-00C04FD65685} HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Wow6432Node\CLSID\{4E3A7680-B77A-11D0-9DA5-00C04FD65685} /s /f
rem IMimeMessage
reg copy HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\REGISTRY\MACHINE\Software\Classes\Wow6432Node\CLSID\{9EADBD1A-447B-4240-A9DD-73FE7C53A981} HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Wow6432Node\CLSID\{9EADBD1A-447B-4240-A9DD-73FE7C53A981} /s /f`
I am invoking application like this
MrMapi -Ma -i input.eml -o output.msg -Cc CCSF_SMTP and mrmapi crashes like desribed here:
[https://github.com/stephenegriffin/mfcmapi/issues/54](url)
Do you have any advices on that?
If it is C2R issue - do you have any workarounds on that? How to install Outlook properly, to have your software working properly? Maybe I should start my fresh installation of office on PC from Office 2010 and then I should do upgrade to future versions?
 MrMAPI.exe, ver 17.0.17099.1
OUTLMIME.DLL. ver: 16.0.8730.2046 (from Office 1711)
Thank you for any answer
