### ISSUE TITLE
MrMapi czech characters in filename not processed succesfully

### ISSUE THREAD

**Issue by AndreasKri** [stephenegriffin/mfcmapi#402]
Hello Stephen,

this issue is also connected to the previous one raised before: 
[#392](https://github.com/stephenegriffin/mfcmapi/issues/392)

With the new release MrMapi works fine with german, french and other special characters.
But I'he got some messages with czech character in subject, but mrmapi doesnt's process them correctly.
It still write the correct names after Input file: and Output file:  though
![image](https://user-images.githubusercontent.com/68102607/90032370-99c5de80-dcbe-11ea-9738-37b9e3f11f17.png)

I will try to figure out which character make trouble...

**Comment by AndreasKri** [comment]
Seems that ě,ř and ů do make trouble, as they are not depicted as initially:
![image](https://user-images.githubusercontent.com/68102607/90033974-5bc9ba00-dcc0-11ea-9e05-02266f771cfc.png)

**Comment by stephenegriffin** [comment]
I see we don’t have the diacritics in the output there. Are the actual generated file names also affected? What about the contents? Are they ok?

**Comment by AndreasKri** [comment]
Although "file converted successfully." **No** converted file appears in the directory at all.
Only when I let the script replace the characters, the messages are converted successfully.

**Comment by stephenegriffin** [comment]
Hrm - looks like I may be losing the diacritics early on:
C:\src\mfcmapi>mrmapi -i "ě,ř and ů" -v -no
Mode = 1
options = 0x00000001
Switch: Verbose
Switch: Folder
  arg[0] = 13
Switch: Output
  arg[0] = C:\src\mfcmapi
Switch: Input
  arg[0] = e,r and u
