### ISSUE TITLE
Outlook for macOS support

### ISSUE THREAD

**Issue by seamusdemora** [stephenegriffin/mfcmapi#404]
I've lost a bunch of folders in Outlook. I just got off a support call with Microsoft Exchange Services, and the support engineer tells me that the ***only*** way to fix this problem is with your tool. He also said that your tool is ***only available*** on Windows machines - i.e. it will not run on macOS. 

Can someone confirm that the tool is not available for macOS, and if not do you know of another tool that might perform a similar function on macOS is available. Or - are there plans for porting to macOS?

**Comment by stephenegriffin** [comment]
Sorry. This app is built on mapi, which is part of Outlook for Windows. It’s impossible to port to Mac. Maybe you could use the graph api?

**Comment by seamusdemora** [comment]
@stephenegriffin :  Thanks for the feedback - [is this where I should start](https://docs.microsoft.com/en-us/graph/) for info on graph api? 

And if I might trouble you with one other question: What is it that your program does that recovers lost folders? I know that's a dumb question, but I'm still shocked and astounded that Outlook for Mac can "lose" 40-50 of my folders, yet MS has no solution for that.

**Comment by stephenegriffin** [comment]
I don't know the specifics of your issue. Perhaps the folders have somehow been moved to a location not normally visible in the client, in which case the resolution would be to move them back. Or else maybe they have been marked as hidden, in which case the resolution would be to remove the properties marking them as hidden.

Do you know what happened to lead to the folders being lost?

**Comment by seamusdemora** [comment]
No - I don't know how this happened. It's not my machine, but belongs to a friend & I'm trying to help. I helped her search, but I couldn't find them either. She has said she is certain that she did not delete the folders. And that seems likely to me because it was 15-20 folders missing, but 3 remain! 

After failing in my search, I contacted M'soft's Exchange support (I have an account). The tech support guy mentioned the word "corrupted" referring I think to the database for mail. He was very nice, but in the end, he said they (MS Tech Support) couldn't "recover" the missing/lost/misplaced/hidden folders without `mfcmapi`, and that meant she had to have a Windows machine. Neither of us use Windows any longer, so this is a bit of a roadblock at the moment. 

I find it incredible that MS has no method to resolve these corruption issues for macOS... but then this isn't the first time I've been surprised :) 

Any advice or suggestions will be much appreciated.

**Comment by stephenegriffin** [comment]
I shared this with a Mac EE. Their comments:

> My guess (based on the limited details) is that the folders were not sync’d with Exchange and at some point were deleted.
>
> You should be using Time machine or a similar database backup tool to ensure you don’t lose data.  Time machine is the best IMO.
>
>BTW, if the customer is fairly savvy AND the physical files are still on desk, the customer can navigate the low level structure with MySQL.  Generally speaking it’s rare that the files are still on desk. Outlook 2011 did have a way of restoring database files.
>   https://support.microsoft.com/en-us/office/rebuild-the-office-database-c21643be-0f0d-4997-9ec1-8044080054b0
>
>Here’s an article about the 2016+ version of the database which does silent rebuilds.
>  https://support.microsoft.com/en-us/office/about-the-office-for-mac-database-62dd4473-5a7d-407b-b384-1d5f767e8b4b

**Comment by seamusdemora** [comment]
The Time Machine idea is a very good one! She uses Time Machine, and it's set on "autopilot" - will definitely look into this. 

I've also read the article re the 2016+ version. It implies that Microsoft denies the existence of any database problems. Not helpful, and one reason I'm not a MS customer any longer. Oh... wait - I am - I still use MS Outlook :)  Anyway - it just doesn't seem that helpful as it suggests something we've already done, and MS says your software is the only salvation. 

But I do sincerely appreciate your help with this - many thanks!
