### ISSUE TITLE
Import Error IPM.Configuration.Autocomplete

### ISSUE THREAD

**Issue by dvond** [stephenegriffin/mfcmapi#405]
Attempting to import Autocomplete failing with the following error. Any assistance is appreciated.

![image](https://user-images.githubusercontent.com/69986816/90814562-eb89ec80-e2ee-11ea-9b9f-b247b25a71af.png)

**Comment by stephenegriffin** [comment]
Whatever file you’re trying to open is already open in another app. Process explorer can tell you who has it open.
