### ISSUE TITLE
cannot open the item for this reminder

### ISSUE THREAD

**Issue by dbanhhwle** [stephenegriffin/mfcmapi#406]
Hi,

Hoping someone can help with removing an Outlook calendar reminder.
Downloaded and using the 64 bit version of MFCMAPI 20.0.20227.01
When attempting to delete the message with the 'Delete to deleted items' option the following warnings pop up:

_Warning: 
_Code: MAPI_W_PARTIAL_COMPLETION == 0x00040680_
Function lpSourceFolder->CopyMessages( lpEIDs, nullptr, lpWasteFolder, lpProgress ? reinterpret_cast<ULONG_PTR>(hWnd) : NULL, lpProgress, ulCopyFlags)
File D:\a\1\s\core\mapi\mapiFunctions.cpp
Line 1140_

Click OK and then this message pops up:

_Warning: 
Code: MAPI_W_PARTIAL_COMPLETION == 0x00040680
Function mapi::DeleteToDeletedItems(lpMDB, m_lpFolder, lpEIDs, m_hWnd)
File D:\a\1\s\UI\Dialogs\ContentsTable\FolderDlg.cpp
Line 665_

The message doesn't delete.

Using the 'Permanent deletion (deletes to deleted item retention if supported)'  and only the following message pops up:

_Warning: 
Code: MAPI_W_PARTIAL_COMPLETION == 0x00040680
Function m_lpFolder->DeleteMessages( lpEIDs, lpProgress ? reinterpret_cast<ULONG_PTR>(m_hWnd) : NULL, lpProgress, ulFlag)
File D:\a\1\s\UI\Dialogs\ContentsTable\FolderDlg.cpp
Line 677_

Using the last style. i.e. 'Permanent delete passing DELETE_HARD_DELETE (unrecoverable)' whilst no pop ups appear a refresh of the messages view and restart of Outlook reveals that the reminder message is still there.

Can anyone please provide further assistance or guidance.

Thanks

Dat

**Comment by stephenegriffin** [comment]
Reminders aren't distinct objects - they're just props on a meeting. So you don't delete the reminder - you change the props that the reminder search folder is looking for.
