### ISSUE TITLE
Error:  Code: MAPI_E_FAILONEPROVIDER == 0x8004011D

### ISSUE THREAD

**Issue by SafetLi** [stephenegriffin/mfcmapi#407]
I can not open any Mailboxes 

I allways get the Error-Message: 
Error: 
Code: MAPI_E_FAILONEPROVIDER == 0x8004011D
Function lpSession->OpenMsgStore( ulUIParam, lpEID->cb, reinterpret_cast<LPENTRYID>(lpEID->lpb), nullptr, ulFlags, static_cast<LPMDB*>(&lpMDB))
File D:\a\1\s\core\mapi\mapiStoreFunctions.cpp
Line 39

I work as 2nd Level Support and I need MFCMapi to fix some Problems

Actually i have following Outlook Version installed on my Company PC:
Office 365 (16.0.11328.20620) 64-Bit

it have worked fine until yesterday.

A downgrade is of Office is not possible because all PCs of the Company use the same Office Version.

Please can you Help Me with this Prob.

Thank you and greetings from Vienna

**Comment by Navoxctr** [comment]
We are also experiencing the same issue. I love MFCMapi but our org will not let us downgrade the version of outlook. We are currently on MSO (16.0.13801.20240)

Error: 
Code: MAPI_E_FAILONEPROVIDER == 0x8004011D
Function CallOpenMsgStore( lpMAPISession, reinterpret_cast<ULONG_PTR>(m_hWnd), lpEntryID, ulFlags, reinterpret_cast<LPMDB*>(lppMAPIProp))
File Dialogs\ContentsTable\MainDlg.cpp
Line 420

**Comment by stephenegriffin** [comment]
MAPI doesn't allow non-office apps to prompt for modern auth. You gotta open the profile with Outlook first to cache creds. If you're trying to bypass cache and go online, then you need to open Outlook with an online profile to cache those creds.

**Comment by Navoxctr** [comment]
This issue resolved itself and then recently came back.   To troubleshoot I uninstalled office 32 bit and installed office 64 bit and I am still having this issue. 

Version of office installed. 
 
Version 2105 (Build 14026.20308 Click-to-run)
Microsoft® Outlook® for Microsoft 365 MSO (16.0.14026.20294) 64-bit 

Outlook is setup in Cached mode. Outlook mailbox is fully loaded. 

I opened outlook to cache the creds and then opened mfcmapi and still received this error. 

Error: 
Code: MAPI_E_FAILONEPROVIDER == 0x8004011D
Function lpSession->OpenMsgStore( ulUIParam, lpEID->cb, reinterpret_cast<LPENTRYID>(lpEID->lpb), nullptr, ulFlags, static_cast<LPMDB*>(&lpMDB))
File D:\a\1\s\core\mapi\mapiStoreFunctions.cpp
Line 39


Is there anything else I need to configure in mfcmapi to resolve this? I use mfcmapi on a daily basis and love this tool I just need to know what I can do to resolve this short of going to find an older outlook 2013 client. I know it works with outlook 2013 connected to an o365 account.

**Comment by Navoxctr** [comment]
> MAPI doesn't allow non-office apps to prompt for modern auth. You gotta open the profile with Outlook first to cache creds. If you're trying to bypass cache and go online, then you need to open Outlook with an online profile to cache those creds.

This doesn't resolve the issue.

**Comment by SafetLi** [comment]
Hi all,

i have solve this problem by reinstalling windows on my pc 
since then MfcMapi works fine on my workstation
