### ISSUE TITLE
Need help with creating contacts in Outlook address book via MAPI

### ISSUE THREAD

**Issue by Robert-McG** [stephenegriffin/mfcmapi#427]
Hi there,

I saw the "Find a bug? Need help? Have a suggestion? Report your issues through the issues tab", so I hope you don't mind me asking here.

Our group is currently working on Thunderbird's MAPI code that accesses the Outlook address book. So far, we can retrieve contacts from the Outlook address book and edit and delete them. Creating new contacts fails.

Here is the code:
https://searchfox.org/comm-central/rev/7ef1ff19561370e6cc7d7aa1939cdc7ebda11bcc/mailnews/addrbook/src/nsAbWinHelper.cpp#566

That first opens the AB container, and then tries to retrieve its `PR_DEF_CREATE_MAILUSER` property. That call fails, either with MAPI_W_ERRORS_RETURNED, or in another version of Outlook is seems to succeed, but PT_ERROR is returned in the property type, so the retrieval failed.

The code looks as if it would follow this documentation:
https://docs.microsoft.com/en-us/office/client-developer/outlook/mapi/creating-a-recipient

I've spent quite some time looking for sample code using `PR_DEF_CREATE_MAILUSER` and didn't find any. Also in this project, it's not used. I have the feeling that calling `GetProps()` on the AB container might the the wrong thing to do since the documentation says "An address book provider's PR_DEF_CREATE_MAILUSER ... propert[y]", and the container is not the provider, or is it? 

I tried to follow the documentation here:
https://docs.microsoft.com/en-us/previous-versions/office/developer/office-2007/cc678348(v=office.12)?redirectedfrom=MSDN#running-mfcmapi
with MFCMAPI, but there is no add-ins menu. There is "New > Contact" on the folder menu
![image](https://user-images.githubusercontent.com/76407651/102723406-f63da800-4307-11eb-9bef-55e2d11a437c.png)
but that seems to launch Outlook and it's not possible to create a contact that way since "Save and Close" is not enabled. Even it it were, it wouldn't help with my investigation.

Any hint would be much appreciated.

**Comment by Robert-McG** [comment]
I've done a search on https://peach.ease.lsoft.com/Archives/mapi-l.html. That yielded some hits, including:
https://peach.ease.lsoft.com/scripts/wa-PEACH.exe?A2=ind0706&L=MAPI-L&P=R353
https://peach.ease.lsoft.com/scripts/wa-PEACH.exe?A2=ind9609&L=MAPI-L&P=R8715
https://peach.ease.lsoft.com/scripts/wa-PEACH.exe?A2=ind0102&L=MAPI-L&P=R5412

The last two have a `GetPAB()` call before the `GetProps()` call with `PR_DEF_CREATE_MAILUSER` and it still fails. According to my code inspection, the right address book should have already been passed into the function, but harm using the PAB directly for a test.

**Comment by stephenegriffin** [comment]
I'm not aware of any modern AB provider that exposes PR_DEF_CREATE_MAILUSER. You should look at the code in MFCMAPI behind that New Contact menu option. It does what you want.

**Comment by Robert-McG** [comment]
Thanks, Steven. You're referring to the "New > Contact" menu option shown in the screenshot in the initial comment? I've just checked in "Process Explorer": That launches Outlook's contacts panel, only that "Save & Close" is not enabled. So that doesn't look like some external MAPI program would create the contact. Could you please include a link to the relevant code or name the source file and line number. Thank you in advance.
