### ISSUE TITLE
Figure Out Collapsing For Restriction Editor

### ISSUE THREAD

**Issue by stephenegriffin** [stephenegriffin/mfcmapi#45]
Migrated from https://mfcmapi.codeplex.com/workitem/16672
Even after all the collapsing work, the restriction editor needs serious help. Figure something out.

**Comment by desjarlais** [comment]
What kind of collapsing were you thinking about doing?

**Comment by stephenegriffin** [comment]
Take a look at the hex editor - each of those sections can be collapsed by clicking on the blue part of the header. I did the same work on the restriction editor, but it still ends up super tall. It'd be nice to collapse all but the actual restriction.

This may be an easy/simple rearrangement of the current dialog, or it may require new engineering work to allow sections that weren't collapsible to be collapsible. I just never looked in to it.

**Comment by desjarlais** [comment]
Will do, if I think I can figure out a way to implement a different approach I'll make a PR so you can review it and go from there.
