### ISSUE TITLE
Error code: STG_E_INVALIDNAME == 0x800300FC when selecting several files

### ISSUE THREAD

**Issue by OlegD94** [stephenegriffin/mfcmapi#468]
Hello,

When I try to import all Quick steps .msg files at once, I receive the following error:

Error: 
Code: STG_E_INVALIDNAME == 0x800300FC
Function MyStgOpenStorage(szMessageFile, true, &pStorage)
File D:\a\1\s\core\mapi\mapiFile.cpp
Line 50

No issues when I am adding files one by one. 

I suspect it has something to do with File name field, since it takes all name files in one long:
![image](https://user-images.githubusercontent.com/83699653/117124573-cebc1900-ad98-11eb-9d5a-95cd5720bf94.png)

Is there a way to bypass it? Or am I doing something wrong?

**Comment by stephenegriffin** [comment]
That's the old file dialog, which I just moved away from. Do you still repro with the may 2021 release?

**Comment by OlegD94** [comment]
My bad, I thought I got the latest version. 
Thank you.
