### ISSUE TITLE
Outlook 2016

### ISSUE THREAD

**Issue by PhilipBrooks** [stephenegriffin/mfcmapi#47]
Trying to use MFCMapi for the first time on Windows 10 and Outlook 2016. Getting error messages when trying to logon. Most recent error "Outlook cannot log on. Verify you are connected to the network and are using the proper server and mailbox name..." Is there something special I need to do on Windows 10/Outlook 2016? 

![capture](https://cloud.githubusercontent.com/assets/27778341/25191374/5afe02c6-24fd-11e7-93b5-a61e19ed9bb1.PNG)

**Comment by stephenegriffin** [comment]
Is Outlook working with the same profile?

**Comment by PhilipBrooks** [comment]
No, and I should have been clearer on this issue. My apologies.

I log into MFCMapi with my admin account, which is a different profile than my normal Outlook account profile. So when I log onto a session nothing comes up, and when I try to connect to another users mailbox for troubleshooting, I get the error message: [cid:image002.png@01D2B9B1.9718F1B0]

**Comment by stephenegriffin** [comment]
What happens when you try this profile with Outlook?

**Comment by stephenegriffin** [comment]
no repro - no details - not MFCMAPI
