### ISSUE TITLE
Why is RegFlushKey() called after DeleteProfile() and SetDefaultProfile()?

### ISSUE THREAD

**Issue by eesheesh** [stephenegriffin/mfcmapi#487]
MFCMAPI code (for example, [here](https://github.com/stephenegriffin/mfcmapi/blob/c88a46b3b46629b98d5a09f0e787f2e1d052c355/core/mapi/mapiProfileFunctions.cpp#L367)) calls `RegFlushKey()` after `DeleteProfile()` and `SetDefaultProfile()`. There's no comment or documentation (that I could find) explaining why that's done or if it's necessary.

Would it be possible to add something to the docs, or a code comment explaining when it's required?

**Comment by stephenegriffin** [comment]
As noted in the [RegFlushKey ](https://docs.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regflushkey) docs it just ensures the changes are written to disk. Is it causing a problem?

**Comment by eesheesh** [comment]
No, not at all - just curious as to why it's required (and if it's required at all). My assumption was that if it's required, then it would already be called by `DeleteProfile()` and `SetDefaultProfile()` themselves, or that the docs for these functions would explicitly say that `RegFlushKey()` should be called after them. Not seeing either of those made me wonder what's the best way to handle it, that's all. :) Feel free to close this out, thanks!

**Comment by stephenegriffin** [comment]
I probably observed at one point the changes weren't committed immediately and this caused refresh issues in mfcmapi - something like that. Would have been nice if I left a comment in there. :)
