### ISSUE TITLE
MFCMapi not working to delete Purge Folder

### ISSUE THREAD

**Issue by BillRoz** [stephenegriffin/mfcmapi#489]
We have been having a few users where the purge folder gets too large and users cannot delete or use calendar. In the past (month or so ago) we have used this tool to delete purge folder. While it did take some time it worked wonderfully. Now all the sudden it will work at all. I can go through the process and when I get to deleting purges if I try to delete all at once it just locks up. If I leave it long enough I get messages like Partial completion or completion with  what looks like error codes, but nothing id removed. If I try to delete 1 at a time, it never deletes and I get no messages. 

I have tried this on both my work PC and my home PC to try and see if maybe work was now blocking it or something. I jjust do not understand why it worked about a month ago and now all the sudden it does not.  
![mfcmaipi1](https://user-images.githubusercontent.com/89303762/130322113-2af49a41-7e1c-43c1-8ebc-06d91bc27404.png)

**Comment by stephenegriffin** [comment]
All MFCMAPI does here is ask the server to empty the folder. Any failure is coming back from the server, so it sounds like something's changed server side. You might try running fiddler and peak into the request/response for the rops (https://github.com/OfficeDev/Office-Inspectors-for-Fiddler) to see if Exchange returned a better failure code or even a stack.
