### ISSUE TITLE
Error when trying to convert MSG to EML

### ISSUE THREAD

**Issue by lukescammell** [stephenegriffin/mfcmapi#49]
Hi, thank you for creating this and providing it free of charge!

I'm trying to convert an MSG file to EML but I'm running into an error. I'm running Outlook 2016 x64 in a Windows Domain on Windows 10 version 1703.

1. I fire up MFCMAPI.exe x64 version 17.0.17099.1
2. go to **Advanced → Import / Export → Convert MSD to EML…**
3. leave all options as default and hit the **OK** button
4. select the test.msg and hit the **Open** button
5. save it as test.eml and hit the **Save** button
6. then I get three errors, listed below in full
7. I hit the **OK** button on each one and that’s it, no EML file created.

### Error 1
```
Error: IConverterSession not found. This interface is only supported by Outlook 2003 and higher.
Code: REGDB_E_CLASSNOTREG == 0x80040154
Function CoCreateInstance(CLSID_IConverterSession, nullptr, CLSCTX_INPROC_SERVER, IID_IConverterSession, reinterpret_cast<LPVOID*>(&lpConverter))
File MapiMime.cpp
Line 82
```

### Error 2
```
Error: 
Code: REGDB_E_CLASSNOTREG == 0x80040154
Function ExportIMessageToEML( pMessage, lpszEMLFile, ulConvertFlags, et, mst, ulWrapLines, lpAdrBook)
File MapiMime.cpp
Line 209
```

### Error 3
```
Error: 
Code: REGDB_E_CLASSNOTREG == 0x80040154
Function ConvertMSGToEML( msgfile.c_str(), emlfile.c_str(), ulConvertFlags, et, mst, ulWrapLines, lpAdrBook)
File Dialogs\ContentsTable\MainDlg.cpp
Line 1715
```

Outlook 2016 x64 is currently running while this happens, but having Outlook closed makes no difference.

The folder I’m trying to write to is in my `%USERPROFILE%\Downloads` directory and has no special permissions (they’re all default).

I’ve added screenshots of each stage in the process just in case that’s helpful.

Once again, thank you very much for this, I can't wait to get it working!

![mfcmapi_2017-05-16_16-34-57](https://cloud.githubusercontent.com/assets/108340/26115548/2a10fbe4-3a58-11e7-99d9-ebe2504a426e.png)

![mfcmapi_2017-05-16_16-36-28](https://cloud.githubusercontent.com/assets/108340/26115489/0600c5e0-3a58-11e7-92b5-7e39d70d8603.png)

![mfcmapi_2017-05-16_16-38-32](https://cloud.githubusercontent.com/assets/108340/26115508/0f5a8bd0-3a58-11e7-8486-78e655218e90.png)

![mfcmapi_2017-05-16_16-38-54](https://cloud.githubusercontent.com/assets/108340/26115512/1398e764-3a58-11e7-8711-d7073c8c711c.png)

![mfcmapi_2017-05-16_16-39-10](https://cloud.githubusercontent.com/assets/108340/26115525/1bbe0c58-3a58-11e7-8849-8388b40aeb3f.png)

![mfcmapi_2017-05-16_16-39-49](https://cloud.githubusercontent.com/assets/108340/26115530/1f44b71e-3a58-11e7-93cc-5d54606554cc.png)

![mfcmapi_2017-05-16_16-39-57](https://cloud.githubusercontent.com/assets/108340/26115536/2339af00-3a58-11e7-9f69-3af5eefabb8d.png)

![mfcmapi_2017-05-16_16-40-06](https://cloud.githubusercontent.com/assets/108340/26115544/26b1c2e4-3a58-11e7-9809-c57b393f1d2a.png)

**Comment by stephenegriffin** [comment]
Outlook is Click2Run - the interface we need isn't exposed. I should look at hiding those menu options in that case

**Comment by lukescammell** [comment]
And another one bites the dust, thanks :(

**Comment by Yoanndp** [comment]
Hi @lukescammell, I see you closed this issue. I have exactly the same problem. How did you resolve this issue ?

**Comment by klishb** [comment]
@stephenegriffin Since Outlook is only distributed as Click2Run these days do you have any suggestions for dealing with this issue?

**Comment by ITfee** [comment]
I too have exactly the same problem.

**Comment by stephenegriffin** [comment]
> i have the same issue anyone heard of how to solve this issue ?

You don't - the feature is not accessible in Outlook anymore so MFCMAPI can't use it.

**Comment by jengelh** [comment]
The workaround is to use OL2016, which is C2R-free.
