### ISSUE TITLE
Unicode / accented characters displayed incorrectly

### ISSUE THREAD

**Issue by Disassembler0** [stephenegriffin/mfcmapi#5]
Unicode characters are garbled in window title, tree view and edit window. However they are OK in the table view. See attached image (Czech Outlook 2016 x64).
![mfcmapi_unicode](https://cloud.githubusercontent.com/assets/5568046/20767059/227ef0f4-b739-11e6-82ee-e069eb2c374a.png)

**Comment by stephenegriffin** [comment]
In the table view, could you open the PR_DISPLAY_NAME property and copy out the hex string so I can use it for testing? Thanks!

**Comment by Disassembler0** [comment]
Hex: 446F7275E8656EE120706F9A7461
Wrong: Doru￨en￡ poﾚta
Correct: Doručená pošta

Hex: 4E6576799EE164616EE120706F9A7461
Wrong: Nevyﾞ￡dan￡ poﾚta
Correct: Nevyžádaná pošta

Hex: 50F8ED6C699A209E6C759D6F75E86BFD206BF9F220FA70EC6C20EFE162656C736BE920F36479
Wrong: P￸￭liﾚ ﾞluﾝou￨k� k￹￲ ￺p￬l ￯￡belsk￩ ￳dy
Correct: Příliš žluťoučký kůň úpěl ďábelské ódy
(Czech variant of "The quick brown fox jumps over a lazy dog".)

If it helps anyhow, the default Czech fallback encoding is Windows-1250.

**Comment by stephenegriffin** [comment]
@Disassembler0 Should be good now - you can build to test if you wanna check before the next release. File a bug if you find any more of these. Thanks!
