### ISSUE TITLE
Missing triangle for subfolders

### ISSUE THREAD

**Issue by WalterHof** [stephenegriffin/mfcmapi#514]
With the latest 32 bit MFCMapi versions I miss the triangle on the left to switch to subfolders. With older MFCMAPI versions e.g. 19.2.19207.938 I find on the left side before "Root Container" a triangle for the subfolders. With the newer versions 21.xxx this triangle is missing. The space is empty. MFCMAPI runs on Windows 10 64 Bit Build: 19043.1320 with Outlook 2010 32 Bit. 

![image](https://user-images.githubusercontent.com/22716404/139539126-d2d9c354-5010-4ad3-ae4f-4e4e1d632388.png)

How do I get the triangle back so I can switch to the subfolders?

**Comment by stephenegriffin** [comment]
Quite odd - I don't repro that here. I'll leave this open to see if anyone else reports it.

If you pretend you had the triangle and click where it ought to be, does it work?

**Comment by WalterHof** [comment]
Stephen,



>>If you pretend you had the triangle and click where it ought to be, does it work?



I downloaded the current MFCMapi version 21..0.21127.3 - yes it works. 









With best regards 

Walter







-----Ursprüngliche Nachricht-----
Von: Stephen ***@***.***>
Gesendet: Dienstag 16. November 2021 16:22
An: stephenegriffin/mfcmapi ***@***.***>
CC: Walter Hofstädtler ***@***.***>; Author ***@***.***>
Betreff: Re: [stephenegriffin/mfcmapi] Missing triangle for subfolders (Issue #514)


Quite odd - I don't repro that here. I'll leave this open to see if anyone else reports it.

If you pretend you had the triangle and click where it ought to be, does it work?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
