### ISSUE TITLE
MFCMAPI crashes when converting MSG File To EML 

### ISSUE THREAD

**Issue by gHensges** [stephenegriffin/mfcmapi#52]
When trying to convert an  MSG-File stored with Office 2016 to EML MFCMAPI crashes with the following Signature:

Problemsignatur:
  Problemereignisname:	APPCRASH
  Anwendungsname:	MFCMAPI.exe
  Anwendungsversion:	17.0.17069.1
  Anwendungszeitstempel:	58c30d16
  Fehlermodulname:	OUTLMIME.DLL
  Fehlermodulversion:	15.0.4937.1000
  Fehlermodulzeitstempel:	591aad8d
  Ausnahmecode:	c0000005
  Ausnahmeoffset:	0000000000026fd1
  Betriebsystemversion:	6.1.7601.2.1.0.256.4
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	f1bb
  Zusatzinformation 2:	f1bbdbeb92ab5ae36524f06de11ab5c2
  Zusatzinformation 3:	4a08
  Zusatzinformation 4:	4a0861c11a656fd9e13d86d0b704ff0b

Please find msg-file attached
[Hi please find invoices attached thanks & enjoy your evening Kerri.zip](https://github.com/stephenegriffin/mfcmapi/files/1115955/Hi.please.find.invoices.attached.thanks.enjoy.your.evening.Kerri.zip)

**Comment by stephenegriffin** [comment]
OUTLMIME.DLL <- Clearly not MFCMAPI
