### ISSUE TITLE
App crashes when clicking on Session>Logon

### ISSUE THREAD

**Issue by nextor11** [stephenegriffin/mfcmapi#527]
When I click on Session>Logon the app freezes for a while and then closes without any error message. This happens on every attempt, not randomly. In Event Viewer I see:

Event ID 1000:

Faulting application name: MFCMapi.exe, version: 21.2.21207.1, time stamp: 0x60ff14d7
Faulting module name: mso20win32client.dll, version: 0.0.0.0, time stamp: 0x61ee3a82
Exception code: 0x023476c3
Fault offset: 0x000000000023988d
Faulting process id: 0x38d4
Faulting application start time: 0x01d818545d36b2d0
Faulting application path: C:\Users\victou\Desktop\Tools\MFCMAPI\MFCMapi.exe
Faulting module path: C:\Program Files\Common Files\Microsoft Shared\Office16\mso20win32client.dll
Report Id: 0d406d0f-e7ff-47e0-a2a4-fdf2fa908278
Faulting package full name: 
Faulting package-relative application ID: 

and Event ID 1001:

Fault bucket 2126899441610180456, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: MFCMapi.exe
P2: 21.2.21207.1
P3: 60ff14d7
P4: mso20win32client.dll
P5: 0.0.0.0
P6: 61ee3a82
P7: 023476c3
P8: 000000000023988d
P9: 
P10: 

Attached files:
\\?\C:\Users\victou\AppData\Local\Temp\{3BF3F36C-4AB6-4C55-A7EC-3F82D8D89F34} - OProcSessId.dat
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c364de50-9a04-4934-8034-46f7236e9b59.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8cf3419c-ba2d-4216-bdaa-b36afd01c3a1.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c63a98a6-3419-483a-b6c6-4e4d7f735679.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0b75adc1-6cec-4135-a164-5b7a24a13d92.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7104dde9-59e2-4249-af99-1112d95ff713.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_MFCMapi.exe_90ee33ab465b542ebb101645d9a1cb8dbe3b195_a098ee4e_59020d14-88b8-49b0-8a99-ebffabf5a784

Analysis symbol: 
Rechecking for solution: 0
Report Id: 0d406d0f-e7ff-47e0-a2a4-fdf2fa908278
Report Status: 268435456
Hashed bucket: 0347d9465759a70f4d8443c5fa26c768
Cab Guid: 0

**Comment by stephenegriffin** [comment]
@nextor11 Can you run procmon while you repro the issue and see if you see mfcmapi trying to load msoaria.dll?

**Comment by nextor11** [comment]
Is this what you asked for?

![image](https://user-images.githubusercontent.com/41907401/152324787-86b0465c-bec7-4338-9e4b-711f2c93b0de.png)

**Comment by nextor11** [comment]
It doesn't crashes anymore If I copy msoaria.dll in the MFCMAPI directory. Thanks!

**Comment by stephenegriffin** [comment]
Cool - this was caused by an Office update which is getting rolled back. Glad to see you found a workaround, but it should no longer be required shortly.
