### ISSUE TITLE
MAPI_E_FAILONEPROVIDER == 0x8004011D when openingen mailbox in Online mode

### ISSUE THREAD

**Issue by KoekieMie** [stephenegriffin/mfcmapi#529]
I've seen older issues ablout this topic and followed the workaround (download latest version of MFCMAPI and restart outlook a few times) but after restarting outlook more than 5 times, I still get the same error.
![image](https://user-images.githubusercontent.com/99338233/153212570-0e9cdde6-8e7f-48fc-96c6-7cf6c73db6b6.png)
Mailbox is in O365 with cached mode.
MFCMAPI is in online mode.
![image](https://user-images.githubusercontent.com/99338233/153212771-958264cf-e907-4ee4-b557-0f24db741f04.png)
![image](https://user-images.githubusercontent.com/99338233/153212942-e77e7de3-4e83-4b3f-b6bf-ef8bf759cd00.png)

**Comment by stephenegriffin** [comment]
you don't have an auth token for online cached and MAPI does not provide a way for MFCMAPi to request one. You can build an online profile and use it once in Outlook to get the token cached and then MFCMAPI should work.

**Comment by KoekieMie** [comment]
Thank you for the answer @stephenegriffin but I don't understand it completely.
What do you mean with "You can build an online profile and use it once in Outlook"?
Do you mean I need to remove the cached option? What if it is blocked by policy?
On the other hand, on another PC using an older 32bit version of MFCMAPI I can connect to the same mailbox.

Thanks in advance for your reply.
