### ISSUE TITLE
Crash on exit MFCMapi (Outlook 2016)

### ISSUE THREAD

**Issue by vitskr** [stephenegriffin/mfcmapi#53]
Hello, 

Outlook 2016 16.0.8229.2073 always crashes when I exit MFCMapi.  I login to simple profile with single PST store configured (no imap4 no exchange etc). When i exit MFCMapi i always get crash at Mso20win32client.dll!61b5854e(). I know this is not MFCMapi bug, but maybe there is some workaround for this? Like some new undocumented flag for MAPILogonEx or Logoff?

Step to reproduce:
1) Have Outlook profile with single local pst store
2) Run MFCMapi
3) Login
4) Exit MFCMapi

It crashes Unhandled exception at 0x61B5854E (Mso20win32client.dll) in MFCMapi.exe: 0xC0000005: Access violation writing location 0x00000000.

**Comment by thims** [comment]
The same with Outlook 16.0.8229.2086.

**Comment by stephenegriffin** [comment]
This should be fixed in Outlook by now.
