### ISSUE TITLE
Error: MAPI_E_FAILONEPROVIDER == 0x8004011D

### ISSUE THREAD

**Issue by LachlanDITM** [stephenegriffin/mfcmapi#530]
Hi Stephen,

First off, really great work on this tool. 
Myself and my users thank you for the ability to keep that all-important AutoComplete list!

I have encountered the following error when attempting to open a user's M365 profile store:

`Error: 
Code: MAPI_E_FAILONEPROVIDER == 0x8004011D
Function lpSession->OpenMsgStore( ulUIParam, lpEID->cb, reinterpret_cast<LPENTRYID>(lpEID->lpb), nullptr, ulFlags, static_cast<LPMDB*>(&lpMDB))
File D:\a\1\s\core\mapi\mapiStoreFunctions.cpp
Line 39`

Any assistance or advice you or  other developers may be able to provide in this matter would be surely useful.

Thank you.

**Comment by KoekieMie** [comment]
I had the same question yesterday [#529](https://github.com/stephenegriffin/mfcmapi/issues/529)
The solution @stephenegriffin suggested isn't completely clear to me.

**Comment by LachlanDITM** [comment]
> I had the same question yesterday [#529](https://github.com/stephenegriffin/mfcmapi/issues/529) The solution @stephenegriffin suggested isn't completely clear to me.

Ah okay, I think it may be related to authorization of the account? Perhaps if this is a stale or not recently logged-in M365 account the token may need to be refreshed to allow MAPI access? I don't entirely understand either to be honest. I would absolutely welcome any further input.

**Comment by LachlanDITM** [comment]
I see that this is a dupe of older closed issues I will close this as I can see that @stephenegriffin has replied to a few of these already. I am thinking it may be to do with the fact that I converted the mailbox to a shared box prior to attempting the backup.
