### ISSUE TITLE
Moving default folders isn't permanent

### ISSUE THREAD

**Issue by kalyway101** [stephenegriffin/mfcmapi#534]
I have noticed that moving default folders (Junk Mail, RSS Subscriptions, etc) underneath another folder only lasts a minute and then is reverted back to it's default location.

Wasn't sure if it was an issue with me or if this happens to others.

**Comment by bradhugh** [comment]
If your mailbox is on Exchange Online, we actually block moving default folders. The more likely scenario is that the delete is failing and it just takes the client a bit to realize that it's still there and show it again.
