### ISSUE TITLE
Error deleting a message

### ISSUE THREAD

**Issue by stil86** [stephenegriffin/mfcmapi#540]
On W10 21H2 x64 with version 21.0.21127.03 x86 when I try to hard delete or simply delete a message ("read" message stuck in outbox of Outlook 2007) I receive this error:
Error: 
Code: MAPI_E_UNKNOWN_FLAGS == 0x80040106
Function m_lpFolder->DeleteMessages( lpEIDs, lpProgress ? reinterpret_cast<ULONG_PTR>(m_hWnd) : NULL, lpProgress, ulFlag)
File D:\a\1\s\UI\Dialogs\ContentsTable\FolderDlg.cpp
Line 678

If I try to delete a single property of a mail I receive two errors:
Error: 
Code: MAPI_E_NO_ACCESS == 0x80070005
Function lpMAPIProp->DeleteProps(&ptaTag, &pProbArray)
File D:\a\1\s\core\mapi\mapiFunctions.cpp
Line 1099

Error: 
Code: MAPI_E_NO_ACCESS == 0x80070005
Function lpPropBag->DeleteProp(propModelData->getPropTag(), propModelData->getName())
File D:\a\1\s\UI\Controls\SortList\SingleMAPIPropListCtrl.cpp
Line 864

**Comment by stephenegriffin** [comment]
"stuck in outbox" implies it's in the submit state. Abort the submit if you want to delete it.
