### ISSUE TITLE
Some folders are not showing

### ISSUE THREAD

**Issue by yanxurui** [stephenegriffin/mfcmapi#541]
Signal (DefaultFolderTypeId is 185) is a non-ipm folder in the root folder.
Get-StoreQuery can find this folder but it's not showing in MFCMAPI.
What's the reason?

![image](https://user-images.githubusercontent.com/12461110/174237649-8e6a3d71-4fdc-4be6-82e5-4fe8f9966045.png)

![image](https://user-images.githubusercontent.com/12461110/174237858-989712d3-0f13-4875-b7cf-a283878086c5.png)

**Comment by stephenegriffin** [comment]
The folder must not be exposed through MAPI.

**Comment by yanxurui** [comment]
@stephenegriffin Why and how is this controlled? Thanks.

**Comment by stephenegriffin** [comment]
server decides what it does and does not expose through MAPI
