### ISSUE TITLE
IAddrBook::Address issue

### ISSUE THREAD

**Issue by thims** [stephenegriffin/mfcmapi#55]
After the latest updates to Outlook 2016 (since 1706), MFCMAPI's "Select a Mailbox" dialogs (QuickStart -> Address Book -> Look up user) shows orange circles for all addressess insead of address object type icons like in Outlook (and in previous Outlook version with MFCMAPI):

![abcircles](https://user-images.githubusercontent.com/1841121/28582859-3d71f5d0-7167-11e7-8ef4-b062bc7e41b5.png) ![aboutlook](https://user-images.githubusercontent.com/1841121/28582862-3ee9ddec-7167-11e7-97ae-d168453b240e.png)

**Comment by stephenegriffin** [comment]
I do repro this, but the bug here would be in Outlook, not MFCMAPI.
