### ISSUE TITLE
MAPIToMIMEStm stopped working in MFCMAPI in recent Outlook versions

### ISSUE THREAD

**Issue by eesheesh** [stephenegriffin/mfcmapi#553]
Hi Stephen,

We noticed that MAPIToMIMEStm stopped working in MFCMAPI in recent Outlook versions.

#### Steps to reproduce:

1. Run MFCMAPI virtualized, so IConverterSession can be initialized. Run this in Start->Run: 
    ```
    "C:\Program Files (x86)\Microsoft Office\root\Client\AppVLP.exe" "C:\Users\Administrator\Desktop\MFCMAPI.exe"
    ```
2. Click "QuickStart".
3. Under "Open folder", choose a folder.
4. If asked to choose a profile, choose the affected profile and click "OK".
5. Find the affected message and right-click it.
6. Click "Export message...".
7. Select "EML file (using IConverterSession)".
8. Select a location for the file.
9. In the "Conversion Flags" field, enter `0x00200022`.
10. Enable "Pass Address Book To Converter".
11. Click "OK".

#### Expected behavior (seen with Outlook version 2204 Build 15128.20248 Click-to-Run): 

An EML file is exported, no error is shown.

#### Actual behavior (seen with Outlook version 2207 Build 15427.20210 Click-to-Run): 

An MFCMAPI error dialog, saying:

>Error:
>
>Code: MAPI_E_CALL_FAILED == 0x80004005
>
>Function lpConverter->MAPIToMIMEStm(lpMsg, lpMimeStm, convertFlags)
>
>File D:\a\1\s\core\mapi\mapiMime.cpp
>
>Line 124

Please let me know if you need more information, or if we should report it elsewhere. Thanks! :)

**Comment by stephenegriffin** [comment]
I can't imagine this would be a supported scenario.
