### ISSUE TITLE
Unable to delete the Archive folder

### ISSUE THREAD

**Issue by edwardforgacs** [stephenegriffin/mfcmapi#555]
It is unfortunately not possible to delete the unwanted Top of Information Store\Archive folder which was created by Exchange 2016 CU7 using MFCMAPI (or any other app or tool I have come across).

This unwanted and confusing folder is documented by Microsoft here. It is no longer being created for new mailboxes created after CU8 but unfortunately anything created before CU8 has this undeletable folder.

https://support.microsoft.com/en-us/topic/unexpected-archive-folder-appears-in-outlook-after-installing-exchange-server-2016-cu7-fa4b6a4c-cbae-9c6e-5c32-2a9fecc0abc2

Even using "Hard Delete" it is not possible to remove using MFC MAPI. Is there any chance of allowing it to be deleted? I note the discussion at https://github.com/stephenegriffin/mfcmapi/issues/196 suggests it should be able to be deleted.

**Comment by stephenegriffin** [comment]
MFCMAPI has nothing to do with this. It's just a tool for driving MAPI. If the server disallows the action there's nothing MFCMAPI can do.
