### ISSUE TITLE
Error attempting to convert MSG 

### ISSUE THREAD

**Issue by michaelhensley** [stephenegriffin/mfcmapi#57]
Using Advanced, Import/Export, Convert MSG to EML, I get the following error:
IConverterSession not found. This interface is only supported by Outlook 2003 or higher.

I'm on Outlook 2016.

[MFCMAPI-converter-error.txt](https://github.com/stephenegriffin/mfcmapi/files/1192225/MFCMAPI-converter-error.txt)

**Comment by stephenegriffin** [comment]
You've got Outlook2 2016 ClickToRun - those interfaces aren't exposed in C2R.

**Comment by michaelhensley** [comment]
Thanks! That is really useful information.
