### ISSUE TITLE
Change Address

### ISSUE THREAD

**Issue by KordyakIM** [stephenegriffin/mfcmapi#58]
Hello.
Help me change address in Outlook.
It is possible to change this program MRMAPI?
As this program may be changed MFCMAPI.
Would like MRMAPI to use GPO.
https://support.microsoft.com/en-us/help/3040795/smtp-address-in-user-s-profile-doesn-t-change-when-primary-email-addre

**Comment by stephenegriffin** [comment]
I'm not sure what you're asking for - is this a feature request?
