### ISSUE TITLE
Error: Code: STG_E_INVALIDNAME == 0x800300FC

### ISSUE THREAD

**Issue by raoulbhatia** [stephenegriffin/mfcmapi#6]
Hi!

I am recovering individual items from Office 365 using Windows 10, Office 2013 and the latest version MFCMapi.exe.16.0.16319.01 that I've downloaded today from your website.

For some objects, I get the following 3 errors that I have to manually acknowledge by clicking OK (3 times).

It very much seems like there is an issue with parsing the subject and generating the .msg filename, i.e. invalid characters; or filepath is too long?

I managed to reduce the amount of errors by exporting to `C:\1\` instead of to my Desktop under `C:\Users\raoul\Desktop\export\`

```
Error: 
Code: STG_E_INVALIDNAME == 0x800300FC
Function MyStgCreateStorageEx( szFileName, STGM_READWRITE | STGM_TRANSACTED | STGM_CREATE, STGFMT_DOCFILE, 0, &myOpts, nullptr, __uuidof(IStorage), reinterpret_cast<LPVOID*>(&pStorage))
File File.cpp
Line 600
```
```
Error: 
Code: STG_E_INVALIDNAME == 0x800300FC
Function CreateNewMSG(szFileName, bUnicode, &pIMsg, &pStorage)
File File.cpp
Line 650
```
```
Error: 
Code: STG_E_INVALIDNAME == 0x800300FC
Function SaveToMSG( lpMessage, szFileName.c_str(), bUnicode, hWnd, false)
File File.cpp
Line 454
```

**Comment by stephenegriffin** [comment]
When prompted for the name of the file to use, I assume you're accepting the default - could you copy it out and paste it here so we can see the file name that got generated?

**Comment by raoulbhatia** [comment]
Thanks @stephenegriffin for your quick reply.

I did not try to recover individual files, but tried to recover *all* items:

1. Logon to the outlook account (Office 365 in my case)
2. Open the store (double click)
3. Go to Root Container / Recoverable Items / Purges
4. Right click -> Export folder -> As MSG files...
5. Uncheck "Save associated items" and "Save as Unicode MSG" (unchecked is the default for both)
6. Choose a folder to export to and wait.

In my case, I was dealing with >10000 deleted emails (IPM.Note) and 15500 overall deleted items (incl. IPM.File, IPM.File.Document, IPM.Schedule.Meeting....., IPM.Contact)

**Comment by stephenegriffin** [comment]
Ew - so were you not able to identify which message caused the problem?

MFCMAPI has logging - you could turn on logging before you do the export - I think that'll log out the subject of the exported message.

**Comment by raoulbhatia** [comment]
@stephenegriffin sorry, I moved all the messages back to a folder that is accessible via Outlook.
Therefore, I cannot reproduce this as of now.
Also, logging does not seem to be enabled by default?

Anyways, my suggestion would be to please add some kind of debug-information in a pop-up-ish dialog in case such an error is triggered. This should then help with debugging.

Also, one could add some information that i.e. the PATH of the folder where messages are saved to also plays a role here - that the overall path+filename length is limited to something around 256 in Windows.

What do you think?

**Comment by stephenegriffin** [comment]
The problem is there are over 400 functions wrapped in the error macro that results in that particular dialog. There's no general purpose solution I could implement - I need to hand tune an error dialog for this particular scenario. And since I don't have a repro for the scenario, anything I write there is a potential time bomb. I'll see if I can hack out a repro and fix the underlying bug. In the meantime, no, debug logging is not on by default - it would fill your drive. But it's easy to turn on and it would definitely have the path information in it.
