### ISSUE TITLE
MrMAPI x64 stopped working after running OffCAT against Outlook

### ISSUE THREAD

**Issue by mobilebyrd** [stephenegriffin/mfcmapi#62]
Anyone have any advice on the issue in the title? 

On a related note, WTH is up with Office 2016 & Win 10. Since installing Windows 10 and Office 2016 all my PCs have become inherently unstable. Whereas I rarely had issues with Windows 7, Windows 10 has problems at least every month. Whereas I rarely had issues with Office 2010/13 (except for Excel) I now have constant issues with all Office applications. I don't run plugins, Safe Mode doesn't help, the software and OS are just unstable and buggy.

Should I upgrade my PCs by reinstalling Windows 7? 
Has anyone found a way to make Office 2016 run correctly for powerusers? 

I've spent over 100 hours with MS Support, not to mention the hours spent troubleshooting things myself, to no avail. I get 1 idiot after another when I call technical support and they never resolve anything. I've reinstalled the OS and Office at least 6 times and nothing changes. I've changed my primary disk to an SSD, added more RAM, run Prime95, memtest, HDTest, etc and found no hardware errors The worst was when MS Office Pro support didn't backup my OneDrive storage account, stated they did and spent time showing me what they said was a backup prior to deleting my files, IRREVOCABLY. They later, in an email, admitted the person who backed up my files to their servers, might not have actually backed them up properly and that 11 months of client files were lost. I've since implemented different caching methods on my local machines, setup a local NAS backup and disconnected OneDrive from my PCs (paying for crap I'm not using). 

I'm just sick of the buggy BS and wondering what else is out there which doesn't suck. Right now, Win 10 and Office 2016 suck for power users. There is better data processing software which is cheaper and, due to the size of the data files I'm processing, It makes sense to move away from Excel for processing and presentations. Outlook is Nice but I'm sure there are competitive options and No, GOOGLE is NOT AN OPTION. Powerpoint is nice but once again there are better applications that do the same thing as good if not better than powerpoint (Prezi was nice when I used it back around 2011). OneNote is nice but it's like a series of good ideas duct-taped together (it's a jack of all trades, master of none).

**Comment by stephenegriffin** [comment]
The issue in the title, mrmapi crashing, is a bug in Outlook. We're working on it.

The rest of the issue, besides not having anything to do with MFCMAPI, doesn't include any details on the problems you're actually having (I'm guessing crashes?). If you just wanted to rant, that's fine, but if you were looking for help you should start by including actual details on what the problem is. But not here - here is for MFCMAPI (and MrMAPI).
