### ISSUE TITLE
CRASH - Cannot login to profile

### ISSUE THREAD

**Issue by glfhern** [stephenegriffin/mfcmapi#66]
After login on to the profile, I cannot open the message store of the user. I get these 2 duplicate errors and then the 3rd:

Error: 
Code: MAPI_E_LOGON_FAILED == 0x80040111
Function CallOpenMsgStore( lpMAPISession, reinterpret_cast<ULONG_PTR>(m_hWnd), lpEntryID, ulFlags, reinterpret_cast<LPMDB*>(lppMAPIProp))
File Dialogs\ContentsTable\MainDlg.cpp
Line 420

Error: 
Code: MAPI_E_LOGON_FAILED == 0x80040111
Function CallOpenMsgStore( lpMAPISession, reinterpret_cast<ULONG_PTR>(m_hWnd), lpEntryID, ulFlags, reinterpret_cast<LPMDB*>(lppMAPIProp))
File Dialogs\ContentsTable\MainDlg.cpp
Line 420

Error: 
Code: MAPI_E_LOGON_FAILED == 0x80040111
Function m_lpContentsTableListCtrl->OpenNextSelectedItemProp( &iItem, mfcmapiREQUEST_MODIFY, &lpMAPIProp)
File Dialogs\ContentsTable\ContentsTableDlg.cpp
Line 255

**Comment by stephenegriffin** [comment]
In what way is this a crash?

**Comment by nikojam** [comment]
Was this ever resolved?  If so what was the actual fix when using the MFCMAPIx86 tool? When I use the the PR_OST_OSTID property is not loaded in the root container hence not locating the needed value to delete.

**Comment by stephenegriffin** [comment]
Please don't resurrect old dead bugs with new issues.
