### ISSUE TITLE
Crash when selecting EntryId in restriction editor dialog

### ISSUE THREAD

**Issue by bradhugh** [stephenegriffin/mfcmapi#67]
MFCMapi x86 Build

Repro:
- Right click search folder
- Edit Search Criteria...
- In "Entry ID List", click Add
*crash*

**Comment by EinmalIM** [comment]
I can repro that with MFCMAPI x64 17.0.17099.01 with MAPI from Outlook 2016 from Office Professional Plus 2016 64-bit 1708 (Build 8431.2079 C2R) Monthly Channel.
