### ISSUE TITLE
MFCMAPI Error: MAPI_E_NOT_ENOUGH_MEMORY == 0x8007000E

### ISSUE THREAD

**Issue by stuajnht** [stephenegriffin/mfcmapi#68]
Hi,

We have a user who cannot open Outlook using their Exchange account, as the following error is shown:
```
Cannot open your default e-mail folders. There is not enough memory available to perform the operation.
```

When trying to diagnose the problem with MFCMAPI (April 2017 version downloaded from GitHub), the following error is shown:
```
Error:
Code: MAPI_E_NOT_ENOUGH_MEMORY == 0x8007000E
Function CallOpenMsgStore( lpMAPISession, reinterpret_cast<ULONG_PTR>(m_hWnd), lpEntryID, ulFlags, reinterpret_cast<LPMDB*>(lppMAPIProp))
File Dialogs\ContentsTable\MainDlg.cpp
Line 420
```

We are using Outlook 2010 (also happens with Outlook 2016) and Exchange 2013. This is the only user that is having this problem, as everyone else can use Outlook as expected.

To prevent repeating information, please refer to these Edugeek thread posts for more details, solutions attempted and screenshots:
http://www.edugeek.net/forums/office-software/182494-outlook-not-enough-memory-available.html#post1566511
http://www.edugeek.net/forums/office-software/182494-outlook-not-enough-memory-available.html#post1566768
I am happy to provide more information in this issue thread instead if needed.

Thanking you in advance for any assistance.

**Comment by stephenegriffin** [comment]
https://support.microsoft.com/en-us/help/3046189/you-cannot-start-outlook-in-cached-mode-or-create-a-new-cached-mode-pr

**Comment by stuajnht** [comment]
Hi @stephenegriffin, thanks for responding.

I have tried following the steps in the support article you linked to, but I still receive the same error after double-clicking the email address in step 7. I have tried the steps on various other working accounts and I can continue with them (expanding the root container, selecting the top of information store, etc...)

Please see this video for what is happening: https://youtu.be/TTHZX5sG6Dw
