### ISSUE TITLE
Error Code: MAPI_E_INTERFACE_NOT_SUPPORTED == 0x80004002

### ISSUE THREAD

**Issue by EthericData** [stephenegriffin/mfcmapi#9]
Hi,

When I try to export an Outlook 2016 autocomplete file by following these [instructions](https://www.msoutlook.info/question/backup-and-restore-autocomplete), I get these errors:

Error: 
Code: MAPI_E_INTERFACE_NOT_SUPPORTED == 0x80004002
Function lpSource->CopyTo( 0, NULL, lpExcludedTags, lpProgress ? reinterpret_cast<ULONG_PTR>(hWnd) : NULL, lpProgress, lpGUIDLocal, lpDest, ulCopyFlags, &lpProblems)
File MAPIFunctions.cpp
Line 2717

Error: 
Code: MAPI_E_INTERFACE_NOT_SUPPORTED == 0x80004002
Function CopyTo( hWnd, lpMessage, pIMsg, &IID_IMessage, LPSPropTagArray(&excludeTags), false, bAllowUI)
File File.cpp
Line 676

Error: 
Code: MAPI_E_INTERFACE_NOT_SUPPORTED == 0x80004002
Function SaveToMSG(lpMessage, filename.c_str(), true, m_hWnd, true)
File Dialogs\ContentsTable\FolderDlg.cpp
Line 1575

Can someone help me out? Thanks

**Comment by stephenegriffin** [comment]
Fixed by aa9533e62338f619fc9fb3090d98a657229470c0

**Comment by DomSumner** [comment]
Hi stephenegriffin, thank you for directing me to this thread. Unfortunately I am a complete novice with MFCMAPI. Could you explain please how I would implement the proposed fix?

Kind regards,

Dom
