### ISSUE TITLE
MFCMAPI x86 Crash on "Export store contents to text"

### ISSUE THREAD

**Issue by Vomitus** [stephenegriffin/mfcmapi#98]
I tried to export my store with a handful of mails via "Right Click on store - Export store contents to text" but MFCMAPI always crashes after creating some files with:
Exception thrown at 0x011B5399 in MFCMapi.exe: 0xC0000005: Access violation writing location 0xDDDDDDDD.

If there is a handler for this exception, the program may be safely continued.

[MFCMAPI_Crash_CallStack.txt](https://github.com/stephenegriffin/mfcmapi/files/1481953/MFCMAPI_Crash_CallStack.txt)

**Comment by Vomitus** [comment]
I did a little investigation on the exception. 
It happens in MapiProcessor.cpp - CMAPIProcessor::AddFolderToFolderList - Line 650:
`lpNewNode->szFolderOffsetPath = szFolderOffsetPath;`
Where lpNewNode->szFolderOffsetPath is not initialized as std::wstring because lpNewNode got allocated with MAPIAllocateBuffer in line 636.

I know nothing about MAPIAllocateBuffer but should it really instantiate structs containing complex data types like std::wstring?

**Comment by Vomitus** [comment]
After reading the docu about MAPIAllocateBuffer and fellow APIs I suggest the pull request #99 to fix this issue.

**Comment by stephenegriffin** [comment]
Thanks for finding and investigating this. I see the fix in #99 but I have a different approach in mind that'll keep the wstring.
